import type { Poem } from '@/lib/schemas';

/**
 * Milestone 1 seeds the opening of the most famous of all Arabic odes — the
 * Mu'allaqa of Imru' al-Qais. Each line is one full bayt (sadr + ʿajuz).
 *
 * The text is verbatim and cross-verified across reputable public-domain
 * sources (Arabic Wikisource — proofreader-marked text — corroborated by
 * al-Diwan and Poets Gate). See `source`.
 */
export const poems: Poem[] = [
  {
    id: 'muallaqat-imru-al-qais',
    slug: 'muallaqat-imru-al-qais',
    titleAr: 'مُعلّقة امرئ القيس',
    titleEn: "The Mu'allaqa of Imru' al-Qais",
    poetId: 'imru-al-qais',
    eraId: 'jahili',
    type: 'muallaqa',
    meter: 'الطويل',
    rhyme: "اللام",
    themes: ['ghazal', 'hikma'],
    isMuallaqa: true,
    linesAr: [
      'قِفَا نَبْكِ مِنْ ذِكْرَى حَبِيبٍ ومَنْزِلِ بِسِقْطِ اللِّوَى بَينَ الدَّخُولِ فَحَوْمَلِ',
      'فَتُوْضِحَ فَالمِقْراةِ لمْ يَعْفُ رَسْمُها لِما نَسَجَتْهَا مِنْ جَنُوبٍ وشَمْأَلِ',
      'تَرَى بَعَرَ الأرْآمِ فِي عَرَصَاتِهَا وَقِيْعَانِهَا كَأنَّهُ حَبُّ فُلْفُلِ',
      'كَأنِّي غَدَاةَ البَيْنِ يَومَ تَحَمَّلُوا لَدَى سَمُراتِ الحَيِّ نَاقِفُ حَنْظَلِ',
      'وُقُوْفًا بِها صَحْبِي عَلَيَّ مَطِيَّهُمُ يَقُوْلُوْنَ لا تَهْلِكْ أَسًى وَتَجَمَّلِ',
      'وإِنَّ شِفائِي عَبْرَةٌ مُهَراقَةٌ فَهَلْ عِندَ رَسْمٍ دَارِسٍ مِنْ مُعَوَّلِ',
      'كَدَأْبِكَ مِنْ أُمِّ الحُوَيْرِثِ قَبْلَها وَجارَتِها أُمِّ الرَّبابِ بِمَأْسَلِ',
      'إِذَا قَامَتَا تَضَوَّعَ المِسْكُ مِنهُمَا نَسِيْمَ الصَّبَا جَاءَتْ بِرَيَّا القَرَنْفُلِ',
    ],
    contextAr:
      'مطلع المعلّقة، حيث يقف الشاعر على أطلال الديار يبكي الحبيب الراحل — أشهر استهلالٍ في الشعر العربيّ كلّه.',
    contextEn:
      "The ode's opening, where the poet halts at the ruined campsite weeping for a departed love — the most famous opening in all of Arabic poetry.",
    source: [
      "https://ar.wikisource.org/wiki/معلقة_امرئ_القيس",
      "https://www.aldiwan.net/poem50.html",
    ],
  },
  {
    id: "muallaqat-antara",
    slug: "muallaqat-antara",
    titleAr: "مُعَلَّقَة عَنْتَرَة — هَل غادَرَ الشُعَراءُ مِن مُتَرَدَّمِ",
    titleEn: "The Mu'allaqa of 'Antara — Have the Poets Left Any Spot Unpatched",
    poetId: "antara",
    eraId: "jahili",
    type: "muallaqa",
    meter: "الكامل",
    rhyme: "الميم (الميمية)",
    themes: ["fakhr", "ghazal", "hamasa"],
    linesAr: [
      "هَل غادَرَ الشُعَراءُ مِن مُتَرَدَّمِ أَم هَل عَرَفتَ الدارَ بَعدَ تَوَهُّمِ",
      "يا دارَ عَبلَةَ بِالجَواءِ تَكَلَّمي وَعَمي صَباحاً دارَ عَبلَةَ وَاِسلَمي",
      "فَوَقَفتُ فيها ناقَتي وَكَأَنَّها فَدَنٌ لِأَقضِيَ حاجَةَ المُتَلَوِّمِ",
      "وَتَحُلُّ عَبلَةُ بِالجَواءِ وَأَهلُنا بِالحَزنِ فَالصَمّانِ فَالمُتَثَلَّمِ",
      "حُيِّيتَ مِن طَلَلٍ تَقادَمَ عَهدُهُ أَقوى وَأَقفَرَ بَعدَ أُمِّ الهَيثَمِ",
      "حَلَّت بِأَرضِ الزائِرينَ فَأَصبَحَت عَسِراً عَلَيَّ طِلابُكِ اِبنَةَ مَخرَمِ",
      "عُلِّقتُها عَرَضاً وَأَقتُلُ قَومَها زَعماً لَعَمرُ أَبيكَ لَيسَ بِمَزعَمِ",
    ],
    isMuallaqa: true,
    contextAr: "مطلع معلقة عنترة، يفتتحها بالتساؤل عمّا أبقاه الشعراء من معانٍ، ثم يقف على ديار محبوبته عَبْلة بالجَواء يُحييها ويذكر بُعدها وتعلّقه بها وهو يحارب قومها. وقد رُوي أنّ سبب نظمها أنّ رجلاً من بني عبس عيّره بسواد أمه وزعم أنه لا يقول الشعر، فردّ عليه عنترة بهذه القصيدة فخرًا.",
    contextEn: "The opening of 'Antara's Mu'allaqa: he begins by asking what poetic meaning earlier poets have left unsaid, then halts at the abandoned dwellings of his beloved 'Abla at al-Jawa, greeting them and recalling her distance and his love for her even as he fights her own people. Tradition holds it was composed after a man of Banu 'Abs taunted him for his mother's black skin and claimed he could not compose poetry, prompting 'Antara to answer with this proud qasida.",
    source: [
      "https://ar.wikisource.org/wiki/%D9%87%D9%84_%D8%BA%D8%A7%D8%AF%D8%B1_%D8%A7%D9%84%D8%B4%D8%B9%D8%B1%D8%A7%D8%A1_%D9%85%D9%86_%D9%85%D8%AA%D8%B1%D8%AF%D9%85_(%D9%85%D8%B9%D9%84%D9%82%D8%A9)",
      "https://www.aldiwan.net/poem85.html",
      "https://poetsgate.com/poem.php?pm=10032",
      "https://ar.wikisource.org/wiki/هل_غادر_الشعراء_من_متردم_(معلقة)",
    ],
  },
  {
    id: "muallaqat-zuhayr",
    slug: "muallaqat-zuhayr",
    titleAr: "معلقة زهير بن أبي سلمى",
    titleEn: "The Muʿallaqa of Zuhayr ibn Abi Sulma",
    poetId: "zuhayr",
    eraId: "jahili",
    type: "muallaqa",
    meter: "الطويل (al-Tawil)",
    rhyme: "الميم المكسورة",
    themes: ["hikma", "ghazal"],
    linesAr: [
      "أَمِن أُمِّ أَوفى دِمنَةٌ لَم تَكَلَّمِ بِحَومانَةِ الدُرّاجِ فَالمُتَثَلَّمِ",
      "وَدارٌ لَها بِالرَقمَتَينِ كَأَنَّها مَراجِعُ وَشمٍ في نَواشِرِ مِعصَمِ",
      "بِها العَينُ وَالأَرآمُ يَمشينَ خِلفَةً وَأَطلاؤُها يَنهَضنَ مِن كُلِّ مَجثِمِ",
      "وَقَفتُ بِها مِن بَعدِ عِشرينَ حِجَّةً فَلَأياً عَرَفتُ الدارَ بَعدَ التَوَهُّمِ",
      "أَثافِيَّ سُفعاً في مُعَرَّسِ مِرجَلٍ وَنُؤياً كَجِذمِ الحَوضِ لَم يَتَثَلَّمِ",
      "فَلَمّا عَرَفتُ الدارَ قُلتُ لِرَبعِها أَلا عِم صَباحاً أَيُّها الرَبعُ وَاِسلَمِ",
    ],
    isMuallaqa: true,
    contextAr: "مطلع المعلقة ونسيبها: يقف زهير على ديار محبوبته أمّ أوفى المهجورة بحَومانة الدُرّاج فالمُتَثَلَّم وبالرَّقمَتَين، بعد عشرين عاماً من الفراق، فلا يكاد يعرف منازلها إلا بآثار الأثافي والنُّؤي. والمعلقة قيلت في الأصل في مدح هرم بن سنان والحارث بن عوف لإصلاحهما بين عبس وذبيان بعد حرب داحس والغبراء، وتتخللها أشهر حِكَم زهير.",
    contextEn: "The opening (nasib) of the Muʿallaqa: Zuhayr halts at the deserted dwellings of his beloved Umm Awfa at Hawmanat al-Durraj, al-Mutathallam, and al-Raqmatayn, twenty years after parting, scarcely recognizing the place except by the blackened hearthstones and the trench around the camp. The full ode was composed to praise Harim ibn Sinan and al-Harith ibn ʿAwf for reconciling ʿAbs and Dhubyan after the war of Dahis and al-Ghabra, and it contains Zuhayr's most celebrated lines of wisdom (hikma).",
    source: [
      "https://ar.wikisource.org/wiki/أمن_أم_أوفى_دمنة_لم_تكلم_(معلقة)",
      "https://www.aldiwan.net/poem25065.html",
      "https://en.wikipedia.org/wiki/Zuhayr_bin_Abi_Sulma and https://www.britannica.com/biography/Zuhayr-ibn-Abi-Sulma",
    ],
  },
  {
    id: "al-khansa-qasida",
    slug: "al-khansa-qasida",
    titleAr: "قَذىً بِعَينِكِ أَم بِالعَينِ عُوّارُ",
    titleEn: "Is It a Mote in Your Eye, or an Inflammation",
    poetId: "al-khansa",
    eraId: "jahili",
    type: "qasida",
    meter: "البسيط",
    rhyme: "الراء (عوّار)",
    themes: ["ritha"],
    linesAr: [
      "قَذىً بِعَينِكِ أَم بِالعَينِ عُوّارُ أَم ذَرَفَت إِذ خَلَت مِن أَهلِها الدارُ",
      "كَأَنَّ عَيني لِذِكراهُ إِذا خَطَرَت فَيضٌ يَسيلُ عَلى الخَدَّينِ مِدرارُ",
      "تَبكي لِصَخرٍ هِيَ العَبرى وَقَد وَلَهَت وَدونَهُ مِن جَديدِ التُربِ أَستارُ",
      "تَبكي خِناسٌ فَما تَنفَكُّ ما عَمِرَت لَها عَلَيهِ رَنينٌ وَهيَ مِفتارُ",
      "تَبكي خِناسٌ عَلى صَخرٍ وَحَقَّ لَها إِذ رابَها الدَهرُ إِنَّ الدَهرَ ضَرّارُ",
    ],
    isMuallaqa: false,
    contextAr: "من أشهر مراثي العرب على الإطلاق، رثت بها الخنساء أخاها صخراً سيد قومه. تفتتح القصيدة بسؤال العين عن سبب دمعها، ثم تصف انهمار البكاء وحزنها الدائم على أخيها، وتجعل الدهر هو الجاني الغدّار.",
    contextEn: "One of the most famous elegies in all of Arabic, in which al-Khansa' mourns her brother Sakhr, the chief of his people. The poem opens by asking the eye why it weeps, then describes the unceasing flow of tears and her perpetual grief, casting Fate itself as the treacherous wrongdoer.",
    source: [
      "https://www.aldiwan.net/poem21079.html",
      "https://ar.wikisource.org/wiki/%D9%82%D8%B0%D9%89_%D8%A8%D8%B9%D9%8A%D9%86%D9%83_%D8%A3%D9%85_%D8%A8%D8%A7%D9%84%D8%B9%D9%8A%D9%86_%D8%B9%D9%88%D8%A7%D8%B1",
    ],
  },
  {
    id: "jarir-qasida",
    slug: "jarir-qasida",
    titleAr: "بانَ الخَليطُ وَلَو طُوِّعتُ ما بانا",
    titleEn: "The Loved Ones Departed (Bana al-Khalit)",
    poetId: "jarir",
    eraId: "umawi",
    type: "qasida",
    meter: "البسيط",
    rhyme: "النون (ـانا)",
    themes: ["ghazal"],
    linesAr: [
      "بانَ الخَليطُ وَلَو طُوِّعتُ ما بانا وَقَطَّعوا مِن حِبالِ الوَصلِ أَقرانا",
      "حَيِّ المَنازِلَ إِذ لا نَبتَغي بَدَلاً بِالدارِ داراً وَلا الجيرانِ جيرانا",
      "لَو تَعلَمينَ الَّذي نَلقى أَوَيتِ لَنا أَو تَسمَعينَ إِلى ذي العَرشِ شَكوانا",
      "إِنَّ العُيونَ الَّتي في طَرفِها حَوَرٌ قَتَلنَنا ثُمَّ لَم يُحيِينَ قَتلانا",
      "يَصرَعنَ ذا اللُبَّ حَتّى لا حِراكَ بِهِ وَهُنَّ أَضعَفُ خَلقِ اللَهِ أَركانا",
    ],
    isMuallaqa: false,
    contextAr: "من أشهر قصائد الغزل في العصر الأموي، وفيها البيت الخالد \"إن العيون التي في طرفها حور\" الذي عُدّ من أرقّ ما قالته العرب في وصف فتنة العيون. مطلعها رحيلٌ ووداعٌ للأحبة، ثم ينتقل جرير إلى الشكوى من سحر النظرات التي تصرع العاشق وهي أضعف الخلق.",
    contextEn: "One of the most celebrated love poems of the Umayyad era, containing the immortal verse \"Indeed the eyes whose glance holds languor,\" reckoned among the tenderest the Arabs ever uttered on the bewitching power of a glance. It opens with the departure and farewell of loved ones, then turns to a lover's complaint of glances that fell him though they are the frailest of created things.",
    source: [
      "https://www.aldiwan.net/poem4432.html",
      "https://arabic-poetry.net/poem/1890",
    ],
  },
  {
    id: "al-farazdaq-qasida",
    slug: "al-farazdaq-qasida",
    titleAr: "إِنَّ الَّذي سَمَكَ السَماءَ بَنى لَنا",
    titleEn: "He Who Raised the Heavens Built for Us",
    poetId: "al-farazdaq",
    eraId: "umawi",
    type: "qasida",
    meter: "الكامل",
    rhyme: "ل (اللام)",
    themes: ["fakhr", "hija"],
    linesAr: [
      "إِنَّ الَّذي سَمَكَ السَماءَ بَنى لَنا بَيتاً دَعائِمُهُ أَعَزُّ وَأَطوَلُ",
      "بَيتاً بَناهُ لَنا المَليكُ وَما بَنى حَكَمُ السَماءُ فَإِنَّهُ لا يُنقَلُ",
      "بَيتاً زُرارَةُ مُحتَبٍ بِفِنائِهِ وَمُجاشِعٌ وَأَبو الفَوارِسِ نَهشَلُ",
      "يَلِجونَ بَيتَ مُجاشِعٍ وَإِذا اِحتَبوا بَرَزوا كَأَنَّهُمُ الجِبالُ المُثَّلُ",
      "لا يَحتَبي بِفِناءِ بَيتِكَ مِثلُهُم أَبَداً إِذا عُدَّ الفَعالُ الأَفضَلُ",
      "مِن عِزِّهِم جَحَرَت كُلَيبٌ بَيتَها زَرباً كَأَنَّهُمُ لَدَيهِ القُمَّلُ",
    ],
    isMuallaqa: false,
    contextAr: "من أشهر قصائد الفرزدق في الفخر والنقائض، يفاخر فيها بقومه بني تميم ويهجو غريمه جريراً وقبيلته كُلَيب، فيجعل مجد قومه بناءً رفعه الله مع السماء لا يُنقَل ولا يُطاوَل.",
    contextEn: "One of al-Farazdaq's most famous odes of self-praise and naqa'id, in which he boasts of his tribe Banu Tamim and lampoons his rival Jarir and his clan Kulayb, casting his people's glory as an edifice raised by God alongside the heavens, immovable and unmatched.",
    source: [
      "https://www.aldiwan.net/poem5474.html",
      "https://ar.wikipedia.org/wiki/%D8%A5%D9%86_%D8%A7%D9%84%D8%B0%D9%8A_%D8%B3%D9%85%D9%83_%D8%A7%D9%84%D8%B3%D9%85%D8%A7%D8%A1_%D8%A8%D9%86%D9%89_%D9%84%D9%86%D8%A7",
      "https://ar.wikipedia.org/wiki/إن_الذي_سمك_السماء_بنى_لنا",
    ],
  },
  {
    id: "al-mutanabbi-qasida",
    slug: "al-mutanabbi-qasida",
    titleAr: "على قَدرِ أهلِ العَزمِ تأتي العَزائمُ",
    titleEn: "Resolves Come in the Measure of the Resolute",
    poetId: "al-mutanabbi",
    eraId: "abbasi",
    type: "qasida",
    meter: "الطويل",
    rhyme: "الميم (المطلقة)",
    themes: ["fakhr", "hikma", "hamasa"],
    linesAr: [
      "عَلى قَدرِ أَهلِ العَزمِ تَأتي العَزائِمُ وَتَأتي عَلى قَدرِ الكِرامِ المَكارِمُ",
      "وَتَعظُمُ في عَينِ الصَغيرِ صِغارُها وَتَصغُرُ في عَينِ العَظيمِ العَظائِمُ",
      "يُكَلِّفُ سَيفُ الدَولَةِ الجَيشَ هَمَّهُ وَقَد عَجَزَت عَنهُ الجُيوشُ الخَضارِمُ",
      "وَيَطلُبُ عِندَ الناسِ ما عِندَ نَفسِهِ وَذَلِكَ ما لا تَدَّعيهِ الضَراغِمُ",
      "يُفَدّي أَتَمُّ الطَيرِ عُمراً سِلاحَهُ نُسورُ الفَلا أَحداثُها وَالقَشاعِمُ",
    ],
    isMuallaqa: false,
    contextAr: "قالها المتنبي في مدح سيف الدولة الحمداني مهنّئًا إياه بفتح حصن الحَدَث على الروم سنة 343 هـ، فجاءت من غرر قصائد الفخر والحماسة، يفتتحها بحكمة سائرة في تناسب العزائم مع أهلها والمكارم مع الكرام.",
    contextEn: "Al-Mutanabbi composed this in praise of Sayf al-Dawla al-Hamdani, celebrating his recapture of the fortress of al-Hadath from the Byzantines in 954 CE. It stands among the most famous odes of pride and martial valor, opening with a proverbial line of wisdom: that resolves rise in measure with the resolute, and noble deeds with the noble.",
    source: [
      "https://www.aldiwan.net/poem10524.html",
      "https://ar.wikipedia.org/wiki/%D8%B9%D9%84%D9%89_%D9%82%D8%AF%D8%B1_%D8%A3%D9%87%D9%84_%D8%A7%D9%84%D8%B9%D8%B2%D9%85",
      "https://ar.wikisource.org/wiki/على_قدر_أهل_العزم_تأتي_العزائم",
    ],
  },
  {
    id: "abu-nuwas-qasida",
    slug: "abu-nuwas-qasida",
    titleAr: "يا رَبِّ إِن عَظُمَت ذُنوبي كَثرَةً",
    titleEn: "O Lord, though my sins be great in number",
    poetId: "abu-nuwas",
    eraId: "abbasi",
    type: "qasida",
    meter: "الكامل",
    rhyme: "الميم (م)",
    themes: ["hikma", "ritha"],
    linesAr: [
      "يا رَبِّ إِن عَظُمَت ذُنوبي كَثرَةً فَلَقَد عَلِمتُ بِأَنَّ عَفوَكَ أَعظَمُ",
      "إِن كانَ لا يَرجوكَ إِلّا مُحسِنٌ فَبِمَن يَلوذُ وَيَستَجيرُ المُجرِمُ",
      "أَدعوكَ رَبِّ كَما أَمَرتَ تَضَرُّعاً فَإِذا رَدَدتَ يَدي فَمَن ذا يَرحَمُ",
      "ما لي إِلَيكَ وَسيلَةٌ إِلّا الرَجا وَجَميلُ عَفوِكَ ثُمَّ أَنّي مُسلِمُ",
    ],
    isMuallaqa: false,
    contextAr: "من أشهر زهديات أبي نواس وتوبياته، يُروى أنها وُجدت مكتوبة بخطّه تحت رأسه بعد موته. الأبيات تضرّعٌ خالصٌ يعترف فيه الشاعر بكثرة ذنوبه ويقابلها برجاء عفو الله الذي هو أعظم، فلا ملاذ للمذنب إلا رحمة ربّه.",
    contextEn: "Among Abu Nuwas's most famous ascetic and penitential verses, said to have been found written in his own hand beneath his head after his death. The lines are a pure supplication in which the poet confesses the magnitude of his sins yet sets against them his hope in God's even greater forgiveness, for the sinner has no refuge but his Lord's mercy.",
    source: [
      "https://www.aldiwan.net/poem27209.html",
      "https://www.aldiwan.net/quote611.html",
    ],
  },
  {
    id: "al-maarri-qasida",
    slug: "al-maarri-qasida",
    titleAr: "غَيرُ مُجدٍ في مِلَّتي واعتِقادي",
    titleEn: "Neither in My Faith nor My Belief Does It Avail",
    poetId: "al-maarri",
    eraId: "abbasi",
    type: "qasida",
    meter: "الخفيف (al-Khafif)",
    rhyme: "الدال",
    themes: ["hikma"],
    linesAr: [
      "غَيرُ مُجدٍ في مِلَّتي واعتِقادي نَوحُ باكٍ ولا تَرَنُّمُ شادِ",
      "وَشَبيهٌ صَوتُ النَّعِيِّ إذا قِيـسَ بِصَوتِ البَشيرِ في كُلِّ نادِ",
      "أَبَكَت تِلكُمُ الحَمامَةُ أَم غَنَّت عَلى فَرعِ غُصنِها المَيّادِ",
      "صاحِ هَذي قُبورُنا تَملأُ الرُّحـبَ فَأَينَ القُبورُ مِن عَهدِ عادِ",
      "خَفِّفِ الوَطءَ ما أَظُنُّ أَديمَ الـأَرضِ إِلّا مِن هَذِهِ الأَجسادِ",
      "سِر إِنِ اِسطَعتَ في الهَواءِ رُوَيداً لا اِختِيالاً عَلى رُفاتِ العِبادِ",
    ],
    isMuallaqa: false,
    contextAr: "مطلعُ داليّةٍ شهيرةٍ من ديوان «سقط الزند»، قالها المعري في رثاء فقيهٍ حنفيٍّ من معرّة النعمان (أبي حمزة)، فجاءت تأمّلاً فلسفيّاً في الموت والفناء وزوال الأمم؛ ومن أبياتها الخالدة «خَفِّفِ الوَطءَ...» التي يدعو فيها إلى التواضع لأنّ تراب الأرض إنما هو رفاتُ مَن سبقونا.",
    contextEn: "The opening of a celebrated dal-rhymed ode from the diwan Saqt al-Zand, composed by al-Maʿarri as an elegy for a Hanafi jurist of Maʿarrat al-Nuʿman (Abu Hamza). It turns into a philosophical meditation on death, mortality, and the passing of nations; among its immortal lines is 'Tread lightly...', urging humility because the dust of the earth is the remains of those who came before us.",
    source: [
      "https://www.aldiwan.net/poem23625.html",
      "https://almaarri.com/poem/%D8%BA%D9%8A%D8%B1-%D9%85%D8%AC%D8%AF-%D9%81%D9%8A-%D9%85%D9%84%D8%AA%D9%8A-%D9%88%D8%A7%D8%B9%D8%AA%D9%82%D8%A7%D8%AF%D9%8A/",
      "https://poetsgate.com/poem.php?pm=74857",
      "https://ar.wikipedia.org/wiki/أبو_العلاء_المعري",
    ],
  },
  {
    id: "ibn-zaydun-qasida",
    slug: "ibn-zaydun-qasida",
    titleAr: "نونية ابن زيدون",
    titleEn: "The Nuniyya of Ibn Zaydun",
    poetId: "ibn-zaydun",
    eraId: "andalusi",
    type: "qasida",
    meter: "البسيط",
    rhyme: "النون (ـينا)",
    themes: ["ghazal"],
    linesAr: [
      "أَضحى التَنائي بَديلاً مِن تَدانينا وَنابَ عَن طيبِ لُقيانا تَجافينا",
      "أَلّا وَقَد حانَ صُبحُ البَينِ صَبَّحَنا حَينٌ فَقامَ بِنا لِلحَينِ ناعينا",
      "مَن مُبلِغُ المُلبِسينا بِاِنتِزاحِهِمُ حُزناً مَعَ الدَهرِ لا يَبلى وَيُبلينا",
      "أَنَّ الزَمانَ الَّذي مازالَ يُضحِكُنا أُنساً بِقُربِهِمُ قَد عادَ يُبكينا",
      "غيظَ العِدا مِن تَساقينا الهَوى فَدَعَوا بِأَن نَغَصَّ فَقالَ الدَهرُ آمينا",
      "فَاِنحَلَّ ما كانَ مَعقوداً بِأَنفُسِنا وَاِنبَتَّ ما كانَ مَوصولاً بِأَيدينا",
    ],
    isMuallaqa: false,
    contextAr: "نظمها ابن زيدون بعد فراقه ونفيه عن قرطبة بُعدًا عن حبيبته ولّادة بنت المستكفي، يندب فيها زمن الوصال ويبكي أيامهما، وهي من أشهر قصائد الغزل في الشعر العربي.",
    contextEn: "Ibn Zaydun composed this poem after his separation and exile from Cordoba, far from his beloved Wallada bint al-Mustakfi; in it he laments the lost time of their union and weeps for their days together. It is among the most famous love poems in all of Arabic literature.",
    source: [
      "https://www.aldiwan.net/poem11836.html",
      "https://ar.wikisource.org/wiki/%D9%86%D9%88%D9%86%D9%8A%D8%A9_%D8%A7%D8%A8%D9%86_%D8%B2%D9%8A%D8%AF%D9%88%D9%86",
      "https://ar.wikisource.org/wiki/نونية_ابن_زيدون",
    ],
  },
  {
    id: "shawqi-qasida",
    slug: "shawqi-qasida",
    titleAr: "وُلِدَ الهُدى فَالكائِناتُ ضِياءُ",
    titleEn: "The Guide Was Born, and All Creation Turned to Light",
    poetId: "shawqi",
    eraId: "hadith",
    type: "qasida",
    meter: "الكامل",
    rhyme: "ء (الهمزة)",
    themes: ["hikma", "fakhr"],
    linesAr: [
      "وُلِدَ الهُدى فَالكائِناتُ ضِياءُ وَفَمُ الزَمانِ تَبَسُّمٌ وَثَناءُ",
      "الروحُ وَالمَلَأُ المَلائِكُ حَولَهُ لِلدينِ وَالدُنيا بِهِ بُشَراءُ",
      "وَالعَرشُ يَزهو وَالحَظيرَةُ تَزدَهي وَالمُنتَهى وَالسِدرَةُ العَصماءُ",
      "وَحَديقَةُ الفُرقانِ ضاحِكَةُ الرُبا بِالتُرجُمانِ شَذِيَّةٌ غَنّاءُ",
      "وَالوَحيُ يَقطُرُ سَلسَلاً مِن سَلسَلٍ وَاللَوحُ وَالقَلَمُ البَديعُ رُواءُ",
      "نُظِمَت أَسامي الرُسلِ فَهيَ صَحيفَةٌ في اللَوحِ وَاِسمُ مُحَمَّدٍ طُغَراءُ",
    ],
    isMuallaqa: false,
    contextAr: "قصيدة همزية في مدح النبي محمد ﷺ، نظمها شوقي معارضةً للهمزية النبوية للإمام البوصيري، وهي من أشهر المدائح النبوية في الشعر الحديث، غنّت بعض أبياتها أم كلثوم. يصوّر المطلع إشراق الكون كله بمولد النبي وبشارة الملائكة والوحي به.",
    contextEn: "A hamziyya in praise of the Prophet Muhammad, composed by Shawqi in emulation of Imam al-Busiri's Prophetic Hamziyya, and among the most famous devotional panegyrics of modern Arabic poetry; some of its verses were sung by Umm Kulthum. The opening depicts the entire cosmos lit up at the Prophet's birth, with the angels and revelation rejoicing in him.",
    source: [
      "https://www.aldiwan.net/poem20977.html",
      "https://arz.wikipedia.org/wiki/ولد_الهدى",
    ],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'muallaqat-tarafa',
    slug: 'muallaqat-tarafa',
    titleAr: 'معلقة طرفة بن العبد',
    titleEn: 'The Muʿallaqa of Tarafa ibn al-ʿAbd',
    poetId: 'tarafa',
    eraId: 'jahili',
    type: 'muallaqa',
    meter: '__PENDING_VERIFICATION__',
    rhyme: '__PENDING_VERIFICATION__',
    themes: ['fakhr', 'hikma'],
    linesAr: ['__PENDING_VERIFICATION__'],
    isMuallaqa: true,
    contextAr: '__PENDING_VERIFICATION__',
    contextEn: '__PENDING_VERIFICATION__',
    source: ['__PENDING_VERIFICATION__', '__PENDING_VERIFICATION__'],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'muallaqat-labid',
    slug: 'muallaqat-labid',
    titleAr: 'معلقة لبيد بن ربيعة',
    titleEn: 'The Muʿallaqa of Labid ibn Rabiʿa',
    poetId: 'labid',
    eraId: 'jahili',
    type: 'muallaqa',
    meter: '__PENDING_VERIFICATION__',
    rhyme: '__PENDING_VERIFICATION__',
    themes: ['hikma', 'fakhr'],
    linesAr: ['__PENDING_VERIFICATION__'],
    isMuallaqa: true,
    contextAr: '__PENDING_VERIFICATION__',
    contextEn: '__PENDING_VERIFICATION__',
    source: ['__PENDING_VERIFICATION__', '__PENDING_VERIFICATION__'],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'muallaqat-amr-ibn-kulthum',
    slug: 'muallaqat-amr-ibn-kulthum',
    titleAr: 'معلقة عمرو بن كلثوم',
    titleEn: 'The Muʿallaqa of ʿAmr ibn Kulthum',
    poetId: 'amr-ibn-kulthum',
    eraId: 'jahili',
    type: 'muallaqa',
    meter: '__PENDING_VERIFICATION__',
    rhyme: '__PENDING_VERIFICATION__',
    themes: ['fakhr', 'hamasa'],
    linesAr: ['__PENDING_VERIFICATION__'],
    isMuallaqa: true,
    contextAr: '__PENDING_VERIFICATION__',
    contextEn: '__PENDING_VERIFICATION__',
    source: ['__PENDING_VERIFICATION__', '__PENDING_VERIFICATION__'],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'muallaqat-al-harith',
    slug: 'muallaqat-al-harith',
    titleAr: 'معلقة الحارث بن حِلِّزة',
    titleEn: 'The Muʿallaqa of al-Harith ibn Hilliza',
    poetId: 'al-harith',
    eraId: 'jahili',
    type: 'muallaqa',
    meter: '__PENDING_VERIFICATION__',
    rhyme: '__PENDING_VERIFICATION__',
    themes: ['fakhr', 'hikma'],
    linesAr: ['__PENDING_VERIFICATION__'],
    isMuallaqa: true,
    contextAr: '__PENDING_VERIFICATION__',
    contextEn: '__PENDING_VERIFICATION__',
    source: ['__PENDING_VERIFICATION__', '__PENDING_VERIFICATION__'],
  },
];
