import type { Poet } from '@/lib/schemas';

/**
 * Poets of the Diwan — public-domain classical figures (Jahili → early-modern).
 * Each poem's verse is verbatim and cross-verified against reputable sources;
 * see content/poems.ts for the texts and their `source` URLs.
 */
export const poets: Poet[] = [
  {
    id: 'imru-al-qais',
    slug: 'imru-al-qais',
    nameAr: 'امرؤ القيس',
    nameEn: "Imru' al-Qais",
    eraId: 'jahili',
    birthYear: 501,
    deathYear: 544,
    region: 'نجد',
    bioAr:
      'امرؤ القيس بن حُجر الكِنديّ، من أشهر شعراء الجاهلية وصاحب أولى المعلّقات السبع. يُلقَّب بالملك الضِّلّيل، طاف البلاد يطلب ثأر أبيه، فجمع بين مُلك ضائع وشعرٍ خالد.',
    bioEn:
      "Imru' al-Qais ibn Hujr al-Kindi, among the most famous pre-Islamic poets and author of the first of the seven Mu'allaqat. Called the Wandering King, he roamed the lands seeking vengeance for his father — a lost kingdom and an immortal verse.",
    humanStoryAr:
      'حين بلغه نبأ مقتل أبيه قال كلمته الشهيرة: «ضيّعني صغيرًا، وحمّلني دمه كبيرًا». فقضى عمره بين اللهو والثأر، وبكى الأطلال في مطلعٍ لم يبلغه شاعر بعده.',
    humanStoryEn:
      "When word reached him of his father's murder he uttered his famous line: 'He neglected me as a child, and burdened me with his blood as a man.' He spent his life between revelry and revenge, weeping over the ruins in an opening no poet has since equaled.",
    themes: ['ghazal', 'fakhr', 'hikma'],
    signaturePoemIds: ['muallaqat-imru-al-qais'],
  },
  {
    id: "antara",
    slug: "antara",
    nameAr: "عَنْتَرَة بْن شَدّاد العَبْسِيّ",
    nameEn: "'Antara ibn Shaddad al-'Absi",
    eraId: "jahili",
    birthYear: 525,
    deathYear: 608,
    region: "نجد، شمال شبه الجزيرة العربية (ديار بني عبس)",
    bioAr: "عَنْتَرَة بْن شَدّاد العَبْسِيّ شاعرٌ فارسٌ من شعراء العصر الجاهلي، وُلد لأبٍ عربيٍّ من بني عبس ولأمٍّ حبشيةٍ تُدعى زبيبة، فنشأ عبدًا حتى أعتقه أبوه بعد أن أبلى في الحرب. يُعَدّ من أشهر فرسان العرب وأصحاب المعلقات، اشتهر بشعر الفروسية والحماسة وبغزله العفيف في ابنة عمه عَبْلة. تُعَدّ معلقته «هل غادر الشعراء من متردم» من عيون الشعر العربي، جمع فيها بين رقّة النسيب وعزّة الفخر.",
    bioEn: "'Antara ibn Shaddad al-'Absi was a warrior-poet of the pre-Islamic (Jahili) era, born to an Arab father of the Banu 'Abs tribe and an Ethiopian slave-mother named Zabiba; he lived as a slave until his father freed him after his valor in battle. He became one of the most celebrated knights of the Arabs and an author of one of the Mu'allaqat, renowned for his poetry of chivalry and heroism and his chaste love for his cousin 'Abla. His Mu'allaqa, \"Have the poets left any spot unpatched,\" is counted among the masterpieces of Arabic verse, blending tender love-prelude with fierce self-praise.",
    humanStoryAr: "عشِق عنترة ابنة عمه عَبْلة عشقًا عفيفًا، لكن أصله المُستعبَد ولونه الأسود حالا دون زواجه منها، فظلّ يطلب يدها ويُكلَّف بمهور تعجيزية من الغزو والإبل، يخوض الحروب ليُثبت أنّ السيف لا اللون هو ميزان الرجال.",
    humanStoryEn: "'Antara loved his cousin 'Abla with a chaste devotion, but his enslaved origin and black skin barred their marriage; he kept seeking her hand while being set impossible bride-prices of raids and camels, waging war to prove that a man is measured by his sword, not his color.",
    themes: ["fakhr", "ghazal", "hamasa"],
    signaturePoemIds: ["muallaqat-antara"],
  },
  {
    id: "zuhayr",
    slug: "zuhayr",
    nameAr: "زهير بن أبي سلمى",
    nameEn: "Zuhayr ibn Abi Sulma",
    eraId: "jahili",
    birthYear: 520,
    deathYear: 609,
    region: "نجد، جزيرة العرب — Najd, Arabian Peninsula",
    bioAr: "زهير بن أبي سلمى المزني (نحو 520 – 609م) شاعر جاهلي من قبيلة مُزَينة، نشأ في ديار غطفان بنجد، ويُلقَّب بـ«حكيم الشعراء» لما في شعره من حِكَم وأمثال سائرة. كان أبوه شاعراً وخاله شاعراً، ونبغ من بنيه كعب وبجير، وقد أدرك ابنه كعب الإسلام ومدح النبي صلى الله عليه وسلم. اشتهر بتنقيح شعره وتجويده حتى نُسبت إليه «الحوليّات» التي كان ينظمها في حول كامل.",
    bioEn: "Zuhayr ibn Abi Sulma al-Muzani (c. 520–609 CE) was a pre-Islamic poet of the Muzayna tribe who lived among the Ghatafan in Najd, and is nicknamed \"the wise man of the poets\" for the proverbial wisdom that fills his verse. He came from a family of poets—his father and maternal uncle composed verse, and his sons Kaʿb and Bujayr followed him—and his son Kaʿb later embraced Islam and praised the Prophet. He was famed for endlessly polishing his odes, so much so that his finest poems were called \"the year-long ones\" (al-hawliyyat) because he would labour over each for a full year.",
    humanStoryAr: "نظم زهير معلقته بعد أن مزّقت حربُ داحس والغبراء قبيلتَي عبس وذبيان أربعين عاماً، فمدح هرم بن سنان والحارث بن عوف اللذين حقَنا الدماء وحملا الدِّيات من مالهما؛ ويفتتحها بوقوفه على أطلال محبوبته أمّ أوفى بعد عشرين حِجّة، يكاد لا يعرف الديار من طول الفراق.",
    humanStoryEn: "Zuhayr composed his Muʿallaqa after the war of Dahis and al-Ghabra had torn the tribes of ʿAbs and Dhubyan apart for forty years, praising Harim ibn Sinan and al-Harith ibn ʿAwf, the two chiefs who stopped the bloodshed and paid the blood-money from their own wealth; he opens it standing over the ruined abode of his beloved Umm Awfa after twenty years, barely able to recognize the place after so long an absence.",
    themes: ["hikma", "ghazal"],
    signaturePoemIds: ["muallaqat-zuhayr"],
  },
  {
    id: "al-khansa",
    slug: "al-khansa",
    nameAr: "الخَنساء (تُماضِر بنت عمرو)",
    nameEn: "Al-Khansa' (Tumadir bint 'Amr)",
    eraId: "jahili",
    birthYear: 575,
    deathYear: 645,
    region: "نجد، جزيرة العرب (بنو سُليم)",
    bioAr: "الخَنساء هي تُماضِر بنت عمرو بن الحارث بن الشَّريد السُّلَمية، أشهر شاعرة في تاريخ العرب وسيدة شعر الرثاء. عاشت معظم حياتها في الجاهلية ثم أدركت الإسلام وأسلمت ووفدت على النبي صلى الله عليه وسلم. أكثرُ شعرها وأجوده في رثاء أخويها صخر ومعاوية اللذين قُتلا، حتى صار اسمها مقروناً بالحزن والبكاء.",
    bioEn: "Al-Khansa' was Tumadir bint 'Amr ibn al-Harith ibn al-Sharid of the tribe of Sulaym, the most celebrated woman poet in Arab history and the supreme voice of the elegy (ritha'). She lived most of her life in the pre-Islamic era, then embraced Islam and came in delegation to the Prophet. The greatest and finest of her verse is the lament for her two slain brothers, Sakhr and Mu'awiyah, so that her name became bound forever to grief and weeping.",
    humanStoryAr: "قُتل أخوها معاوية، فحرّضت أخاها صخراً على الأخذ بثأره، فثأر له ثم مات متأثراً بجراحه، فبكته الخنساء حتى قيل إنها فقدت بصرها من كثرة الدمع. وفي الإسلام قدّمت أبناءها الأربعة إلى معركة القادسية فاستُشهدوا جميعاً، فقالت: «الحمد لله الذي شرّفني بقتلهم».",
    humanStoryEn: "When her brother Mu'awiyah was killed, she goaded her brother Sakhr into avenging him; Sakhr took the revenge but died of his wounds, and al-Khansa' wept for him until, it is said, she lost her sight from weeping. Under Islam she sent her four sons to the battle of al-Qadisiyya, where all were martyred, and she said: \"Praise be to God who honored me with their deaths.\"",
    themes: ["ritha"],
    signaturePoemIds: ["al-khansa-qasida"],
  },
  {
    id: "jarir",
    slug: "jarir",
    nameAr: "جرير بن عطية",
    nameEn: "Jarir ibn Atiyya",
    eraId: "umawi",
    birthYear: 653,
    deathYear: 728,
    region: "نجد / البصرة (قبيلة تميم)",
    bioAr: "جرير بن عطية الخَطَفي التميمي، من بني يربوع، أحد أعظم شعراء العصر الأموي وأحد أركان النقائض الثلاثة مع الفرزدق والأخطل. وُلد ونشأ في بادية نجد ثم استقر بالبصرة، وبرع في الهجاء والمديح والغزل والرثاء، حتى قيل إنه هَجا نحو ثمانين شاعرًا ولم يصمد أمامه إلا الفرزدق والأخطل. اشتهر بسهولة لفظه ورقة غزله، وامتدت مساجلاته الشعرية قرابة أربعين عامًا فصارت من أشهر المعارك الأدبية في تاريخ العربية.",
    bioEn: "Jarir ibn Atiyya al-Khatafi al-Tamimi, of the Banu Yarbu', was one of the greatest poets of the Umayyad era and one of the three masters of the naqa'id (poetic flytings) alongside al-Farazdaq and al-Akhtal. Born and raised in the Najd desert before settling in Basra, he excelled in satire, panegyric, love poetry, and elegy, and is said to have lampooned some eighty poets, with only al-Farazdaq and al-Akhtal able to withstand him. Famed for the ease of his diction and the tenderness of his ghazal, his poetic duels stretched across roughly forty years and became among the most celebrated literary feuds in Arabic history.",
    humanStoryAr: "عاش جرير حياته في حربٍ شعريةٍ ضروسٍ مع غريمه الفرزدق دامت أربعين عامًا حتى ماتا متقاربين، لكنه خلف وراء هذا الهجاء المرّ غزلًا رقيقًا يفيض حنينًا، كأن بيته الخالد \"إن العيون التي في طرفها حور\" شكوى عاشقٍ صرعته نظرةٌ من أضعف خلق الله.",
    humanStoryEn: "Jarir spent his life locked in a ferocious forty-year poetic war with his rival al-Farazdaq, the two dying not long apart, yet behind that bitter satire he left a tender, yearning ghazal — as if his immortal line \"Indeed the eyes whose glance holds languor\" were the lament of a lover felled by a single look from the frailest of God's creatures.",
    themes: ["ghazal", "hija", "fakhr"],
    signaturePoemIds: ["jarir-qasida"],
  },
  {
    id: "al-farazdaq",
    slug: "al-farazdaq",
    nameAr: "الفرزدق (همّام بن غالب)",
    nameEn: "Al-Farazdaq (Hammam ibn Ghalib)",
    eraId: "umawi",
    birthYear: 641,
    deathYear: 728,
    region: "البصرة، العراق (بنو تميم)",
    bioAr: "همّام بن غالب بن صعصعة الدارمي التميمي، المعروف بالفرزدق، شاعر أموي وُلد قرب البصرة سنة 20 هـ تقريبًا وتوفي بها سنة 110 هـ. يُعدّ من أعظم شعراء العصر الأموي وأحد أركان الفخر والهجاء، حتى قيل: لولا شعر الفرزدق لذهب ثلث لغة العرب. اشتهر بنقائضه الطويلة مع غريمه جرير، وبقصائده في الفخر بقومه بني تميم.",
    bioEn: "Hammam ibn Ghalib al-Darimi al-Tamimi, known as al-Farazdaq, was an Umayyad poet born near Basra around 20 AH (c. 641 CE) and died there in 110 AH (728 CE). He is counted among the greatest poets of the Umayyad age and a master of fakhr (self-praise) and hija (invective); it was said that \"were it not for al-Farazdaq's poetry, a third of the Arabic language would be lost.\" He is most famous for his lifelong poetic duels (naqa'id) with his rival Jarir and for his proud odes celebrating his tribe, Banu Tamim.",
    humanStoryAr: "قضى الفرزدق عمره في صراع شعري عنيف مع غريمه جرير دام نحو خمسين عامًا، يتبادلان النقائض في الفخر والهجاء أمام العرب جميعًا، فكان عداؤهما من أشهر الخصومات الأدبية في تاريخ العربية، ولم يهدأ إلا بموت أحدهما.",
    humanStoryEn: "Al-Farazdaq spent his life locked in a ferocious poetic feud with his rival Jarir that lasted roughly fifty years, the two trading boasts and invectives before all the Arabs; their enmity became one of the most famous literary rivalries in Arabic history, ending only with the death of one of them.",
    themes: ["fakhr", "hija"],
    signaturePoemIds: ["al-farazdaq-qasida"],
  },
  {
    id: "al-mutanabbi",
    slug: "al-mutanabbi",
    nameAr: "أبو الطيب المتنبي",
    nameEn: "Abu al-Tayyib al-Mutanabbi",
    eraId: "abbasi",
    birthYear: 915,
    deathYear: 965,
    region: "الكوفة، العراق",
    bioAr: "أبو الطيب أحمد بن الحسين المتنبي (303-354 هـ / 915-965 م)، من أعظم شعراء العربية على الإطلاق، وُلد بالكوفة ونشأ بها ثم تنقّل بين الشام والعراق وفارس ومصر. اشتهر بمدائحه لسيف الدولة الحمداني في حلب، حيث بلغ ذروة مجده الشعري، وامتاز شعره بالحكمة وعزّة النفس والفخر الشديد بنفسه وبالعرب. قُتل عائدًا إلى العراق سنة 354 هـ، وبقي ديوانه من أكثر دواوين الشعر العربي شرحًا ودراسةً وتداولًا.",
    bioEn: "Abu al-Tayyib Ahmad ibn al-Husayn al-Mutanabbi (915-965 CE) is widely regarded as the greatest of all Arabic poets. Born in Kufa, he wandered across the Levant, Iraq, Persia, and Egypt, reaching the summit of his fame in the court of Sayf al-Dawla al-Hamdani at Aleppo. His verse is celebrated for its wisdom, towering self-pride, and martial grandeur; he was killed on the road back to Iraq in 965, and his Diwan remains among the most studied and quoted in the entire Arabic tradition.",
    humanStoryAr: "عاش المتنبي حياة طموح جامح وكبرياء لا يلين، فطمح إلى الإمارة وعاش ربيع عمره في كنف سيف الدولة قبل أن تفسد العلاقة بسبب الحساد والوشاة، فرحل عنه عاتبًا. وقد قُتل في نهاية المطاف لأنه أبى الفرار من المعركة حين عُيّر ببيته «الخيلُ والليلُ والبيداءُ تعرفني»، فمات وفيًّا لكبريائه.",
    humanStoryEn: "Al-Mutanabbi lived a life of unbending pride and a craving for power, spending his prime in Sayf al-Dawla's court until envy and slander poisoned the bond and drove him away in bitter reproach. In the end he was killed because he refused to flee a fight when taunted with his own verse \"The horse, the night, and the desert know me\" — dying true to the pride he had spent a lifetime singing.",
    themes: ["fakhr", "hikma", "hamasa"],
    signaturePoemIds: ["al-mutanabbi-qasida"],
  },
  {
    id: "abu-nuwas",
    slug: "abu-nuwas",
    nameAr: "أبو نُواس (الحَسَن بن هانئ)",
    nameEn: "Abu Nuwas (al-Hasan ibn Hani)",
    eraId: "abbasi",
    birthYear: 756,
    deathYear: 814,
    region: "العراق (البصرة وبغداد)",
    bioAr: "أبو نُواس الحَسَن بن هانئ الحَكَمي (نحو 756 - 814م)، من أبرز شعراء العصر العباسي ورائد الشِّعر المُحدَث. وُلد في الأهواز ونشأ بالبصرة حيث حفظ القرآن، ثم انتقل إلى بغداد فاتصل بالخليفة هارون الرشيد ثم الأمين. اشتهر بخمرياته ومجونه وحضور بديهته، كما له زهديات وتوبيات في أواخر حياته يتضرّع فيها إلى الله ويرجو عفوه.",
    bioEn: "Abu Nuwas, al-Hasan ibn Hani al-Hakami (c. 756–814 CE), was a leading poet of the Abbasid era and the foremost figure of the \"modern\" (muhdath) style. Born in Ahvaz and raised in Basra, where he memorized the Qur'an, he later moved to Baghdad and attached himself to the caliphs Harun al-Rashid and al-Amin. Famous for his wine poetry (khamriyyat), wit, and libertinism, he also composed ascetic and penitential verses in his later years, pleading for God's mercy and forgiveness.",
    humanStoryAr: "عاش أبو نواس حياة لهوٍ وخمرٍ ومجون، ثم أدركه الندم في أواخر أيامه؛ ويُروى أنه لمّا مات وُجدت تحت رأسه رقعة بخط يده مكتوب فيها هذه الأبيات في التضرّع والتوبة ورجاء عفو الله.",
    humanStoryEn: "Abu Nuwas lived a life of revelry, wine, and dissipation, then remorse overtook him in his final days; it is said that when he died, a scrap of paper in his own hand was found beneath his head bearing these verses of supplication, repentance, and hope in God's forgiveness.",
    themes: ["hikma", "ritha"],
    signaturePoemIds: ["abu-nuwas-qasida"],
  },
  {
    id: "al-maarri",
    slug: "al-maarri",
    nameAr: "أبو العلاء المعري",
    nameEn: "Abu al-ʿAlaʾ al-Maʿarri",
    eraId: "abbasi",
    birthYear: 973,
    deathYear: 1057,
    region: "معرة النعمان، بلاد الشام (Maʿarrat al-Nuʿman, Syria)",
    bioAr: "أبو العلاء أحمد بن عبد الله بن سليمان التنوخي المعري (363–449هـ / 973–1057م) شاعرٌ وفيلسوفٌ ولغويٌّ من عصر الدولة العباسية، وُلد وتُوفّي في معرة النعمان بالشام. كُفّ بصره طفلاً إثر إصابته بالجدري، فلُقّب بـ\"رهين المحبسين\" (العمى ولزومه بيته). من أشهر دواوينه «سقط الزند» و«اللزوميات» (لزوم ما لا يلزم)، ورسالته الفلسفية «رسالة الغفران»، وقد اشتهر بنزعته العقلانية التشاؤمية وتأملاته في الحياة والموت والدين.",
    bioEn: "Abu al-ʿAlaʾ Ahmad ibn ʿAbd Allah al-Tanukhi al-Maʿarri (363–449 AH / 973–1057 CE) was a poet, philosopher, and grammarian of the Abbasid era, born and died in Maʿarrat al-Nuʿman in Syria. Blinded by smallpox as a small child, he came to be called \"the prisoner of two prisons\" (his blindness and his self-imposed seclusion at home). His most famous works are the diwans Saqt al-Zand and al-Luzumiyyat, and the prose Risalat al-Ghufran (Epistle of Forgiveness); he is renowned for his rationalist, pessimistic outlook and his meditations on life, death, and religion.",
    humanStoryAr: "عاش المعري زاهداً معتزلاً عن الناس، نباتيّاً لم يتزوّج ولم يُنجب، وأوصى أن يُكتب على قبره: «هذا جناه أبي عليّ وما جنيتُ على أحد»، احتجاجاً على ما رأى أنه ظلمُ إيجاد الأبناء في عالمٍ مليء بالألم.",
    humanStoryEn: "Al-Maʿarri lived as an ascetic recluse, a vegetarian who never married or had children, and asked that his epitaph read: \"This wrong was done to me by my father, but I wronged no one,\" a protest against what he saw as the injustice of bringing children into a world full of suffering.",
    themes: ["hikma"],
    signaturePoemIds: ["al-maarri-qasida"],
  },
  {
    id: "ibn-zaydun",
    slug: "ibn-zaydun",
    nameAr: "ابن زيدون",
    nameEn: "Ibn Zaydun",
    eraId: "andalusi",
    birthYear: 1003,
    deathYear: 1071,
    region: "الأندلس (قرطبة)",
    bioAr: "أبو الوليد أحمد بن عبد الله بن أحمد بن غالب المخزومي، المعروف بابن زيدون (394–463 هـ / 1003–1070 م)، شاعر ووزير وكاتب أندلسي من قرطبة، يُعدّ من أعظم شعراء الأندلس وأشهر شعراء الغزل في العربية حتى لُقّب بـ«بحتري المغرب». عاش في زمن ملوك الطوائف وتنقّل بين بلاط بني جهور في قرطبة وبني عبّاد في إشبيلية، وامتاز شعره برقّة العاطفة وجزالة اللفظ ووصف الطبيعة. وهو صاحب النونية الخالدة التي نظمها في حبيبته ولّادة بنت المستكفي.",
    bioEn: "Abu al-Walid Ahmad ibn Abdullah al-Makhzumi, known as Ibn Zaydun (1003–1070 CE), was an Andalusian poet, vizier, and prose stylist from Cordoba, regarded as one of the greatest poets of al-Andalus and the foremost master of love poetry (ghazal) in Arabic, earning him the title \"the Buhturi of the West.\" He lived during the era of the Party Kings (muluk al-tawa'if), serving in the courts of the Banu Jahwar of Cordoba and the Banu Abbad of Seville, and his verse is celebrated for its tenderness, polished diction, and descriptions of nature. He is the author of the immortal Nuniyya composed for his beloved, the princess-poet Wallada bint al-Mustakfi.",
    humanStoryAr: "أحبّ ابن زيدون الأميرة الشاعرة ولّادة بنت المستكفي حبًّا عاصفًا، لكنّ الوشاة ومنافسه الوزير ابن عبدوس فرّقوا بينهما، فسُجن ثم نفي عن قرطبة، فنظم نونيته يذوب أسىً على فراقها وذكرى أيامهما الصافية.",
    humanStoryEn: "Ibn Zaydun fell passionately in love with the princess-poet Wallada bint al-Mustakfi, but slanderers and his rival, the vizier Ibn Abdus, drove them apart; imprisoned and then exiled from Cordoba, he poured his anguish at their separation and the memory of their pure days together into his celebrated Nuniyya.",
    themes: ["ghazal"],
    signaturePoemIds: ["ibn-zaydun-qasida"],
  },
  {
    id: "shawqi",
    slug: "shawqi",
    nameAr: "أَحْمَد شَوْقِي",
    nameEn: "Ahmad Shawqi",
    eraId: "hadith",
    birthYear: 1868,
    deathYear: 1932,
    region: "Egypt (Cairo)",
    bioAr: "أحمد شوقي (1868–1932) شاعر وكاتب مسرحي مصري، أشهر شعراء العربية في العصر الحديث، لُقّب بـ«أمير الشعراء» بعد أن بايعه شعراء العرب أميراً عام 1927. وُلد في القاهرة لأب من أصل كردي وأم من أصل تركي يوناني، ونشأ في كنف بلاط الخديوي إسماعيل، ودرس الحقوق في فرنسا. يُعَدّ رائد المسرح الشعري العربي، ومن أبرز أعماله القصيدة الهمزية «وُلِدَ الهُدى» في مدح النبي ﷺ ونهج البردة معارضةً لبردة البوصيري.",
    bioEn: "Ahmad Shawqi (1868–1932) was an Egyptian poet and playwright, the most celebrated Arabic poet of the modern era, acclaimed as \"Prince of Poets\" (Amir al-Shu'ara') when the Arab poets pledged the title to him in 1927. Born in Cairo to a father of Kurdish descent and a mother of Turkish-Greek origin, he was raised within the court of Khedive Ismail and studied law in France. He pioneered Arabic verse drama, and among his most famous works is the hamziyya \"Wulida al-Huda\" in praise of the Prophet, alongside \"Nahj al-Burda,\" composed in emulation of al-Busiri's Burda.",
    humanStoryAr: "نفاه الاحتلال البريطاني إلى إسبانيا سنة 1915 بسبب مواقفه الوطنية المناهضة، فعاش غربةً مريرة بين ربوع الأندلس يحنّ إلى وطنه ونيله، ومن وحي ذلك المنفى استلهم بعضاً من أصدق شعره في الحنين إلى مصر قبل أن يعود إليها سنة 1920.",
    humanStoryEn: "The British occupation exiled him to Spain in 1915 for his defiant patriotic stance, and he lived a bitter estrangement among the ruins of Andalusia, aching for his homeland and the Nile; that exile inspired some of his most heartfelt verse of longing for Egypt before he was permitted to return in 1920.",
    themes: ["hikma", "fakhr"],
    signaturePoemIds: ["shawqi-qasida"],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'tarafa',
    slug: 'tarafa',
    nameAr: 'طَرَفة بن العبد',
    nameEn: 'Tarafa ibn al-ʿAbd',
    eraId: 'jahili',
    region: 'البحرين، شرق جزيرة العرب (بنو بكر)',
    bioAr: '__PENDING_VERIFICATION__',
    bioEn: '__PENDING_VERIFICATION__',
    humanStoryAr: '__PENDING_VERIFICATION__',
    humanStoryEn: '__PENDING_VERIFICATION__',
    themes: ['fakhr', 'hikma'],
    signaturePoemIds: ['muallaqat-tarafa'],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'labid',
    slug: 'labid',
    nameAr: 'لَبيد بن ربيعة',
    nameEn: 'Labid ibn Rabiʿa',
    eraId: 'jahili',
    region: 'نجد، جزيرة العرب (بنو عامر بن صعصعة)',
    bioAr: '__PENDING_VERIFICATION__',
    bioEn: '__PENDING_VERIFICATION__',
    humanStoryAr: '__PENDING_VERIFICATION__',
    humanStoryEn: '__PENDING_VERIFICATION__',
    themes: ['hikma', 'fakhr'],
    signaturePoemIds: ['muallaqat-labid'],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'amr-ibn-kulthum',
    slug: 'amr-ibn-kulthum',
    nameAr: 'عمرو بن كلثوم',
    nameEn: 'ʿAmr ibn Kulthum',
    eraId: 'jahili',
    region: 'الجزيرة العربية (بنو تغلب)',
    bioAr: '__PENDING_VERIFICATION__',
    bioEn: '__PENDING_VERIFICATION__',
    humanStoryAr: '__PENDING_VERIFICATION__',
    humanStoryEn: '__PENDING_VERIFICATION__',
    themes: ['fakhr', 'hamasa'],
    signaturePoemIds: ['muallaqat-amr-ibn-kulthum'],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'al-harith',
    slug: 'al-harith',
    nameAr: 'الحارث بن حِلِّزة اليشكري',
    nameEn: 'Al-Harith ibn Hilliza al-Yashkuri',
    eraId: 'jahili',
    region: 'الجزيرة العربية (بنو بكر بن وائل)',
    bioAr: '__PENDING_VERIFICATION__',
    bioEn: '__PENDING_VERIFICATION__',
    humanStoryAr: '__PENDING_VERIFICATION__',
    humanStoryEn: '__PENDING_VERIFICATION__',
    themes: ['fakhr', 'hikma'],
    signaturePoemIds: ['muallaqat-al-harith'],
  },
  // PLACEHOLDER — replace with verified content
  {
    id: 'al-akhtal',
    slug: 'al-akhtal',
    nameAr: 'الأخطل (غياث بن غوث)',
    nameEn: 'Al-Akhtal (Ghiyath ibn Ghawth)',
    eraId: 'umawi',
    region: 'الجزيرة والشام (بنو تغلب)',
    bioAr: '__PENDING_VERIFICATION__',
    bioEn: '__PENDING_VERIFICATION__',
    humanStoryAr: '__PENDING_VERIFICATION__',
    humanStoryEn: '__PENDING_VERIFICATION__',
    themes: ['hija', 'fakhr'],
    signaturePoemIds: [],
  },
];
