import type { Poet } from '@/lib/schemas';

/**
 * Poets of the Diwan — public-domain classical figures (Jahili → early-modern).
 * Each poem's verse is verbatim and cross-verified against reputable sources;
 * see content/poems.ts for the texts and their `source` URLs.
 */
export const poets: Poet[] = [
  {
    id: 'imru-al-qais',
    slug: 'imru-al-qais',
    nameAr: 'امرؤ القيس',
    nameEn: "Imru' al-Qais",
    eraId: 'jahili',
    birthYear: 501,
    deathYear: 544,
    region: 'نجد',
    bioAr:
      'امرؤ القيس بن حُجر الكِنديّ، من أشهر شعراء الجاهلية وصاحب أولى المعلّقات السبع. يُلقَّب بالملك الضِّلّيل، طاف البلاد يطلب ثأر أبيه، فجمع بين مُلك ضائع وشعرٍ خالد.',
    bioEn:
      "Imru' al-Qais ibn Hujr al-Kindi, among the most famous pre-Islamic poets and author of the first of the seven Mu'allaqat. Called the Wandering King, he roamed the lands seeking vengeance for his father — a lost kingdom and an immortal verse.",
    humanStoryAr:
      'حين بلغه نبأ مقتل أبيه قال كلمته الشهيرة: «ضيّعني صغيرًا، وحمّلني دمه كبيرًا». فقضى عمره بين اللهو والثأر، وبكى الأطلال في مطلعٍ لم يبلغه شاعر بعده.',
    humanStoryEn:
      "When word reached him of his father's murder he uttered his famous line: 'He neglected me as a child, and burdened me with his blood as a man.' He spent his life between revelry and revenge, weeping over the ruins in an opening no poet has since equaled.",
    themes: ['ghazal', 'fakhr', 'hikma'],
    signaturePoemIds: ['muallaqat-imru-al-qais', 'imru-al-qais-ala-im-sabahan', 'imru-al-qais-liman-talal'],
  },
  {
    id: "antara",
    slug: "antara",
    nameAr: "عَنْتَرَة بْن شَدّاد العَبْسِيّ",
    nameEn: "'Antara ibn Shaddad al-'Absi",
    eraId: "jahili",
    birthYear: 525,
    deathYear: 608,
    region: "نجد، شمال شبه الجزيرة العربية (ديار بني عبس)",
    bioAr: "عَنْتَرَة بْن شَدّاد العَبْسِيّ شاعرٌ فارسٌ من شعراء العصر الجاهلي، وُلد لأبٍ عربيٍّ من بني عبس ولأمٍّ حبشيةٍ تُدعى زبيبة، فنشأ عبدًا حتى أعتقه أبوه بعد أن أبلى في الحرب. يُعَدّ من أشهر فرسان العرب وأصحاب المعلقات، اشتهر بشعر الفروسية والحماسة وبغزله العفيف في ابنة عمه عَبْلة. تُعَدّ معلقته «هل غادر الشعراء من متردم» من عيون الشعر العربي، جمع فيها بين رقّة النسيب وعزّة الفخر.",
    bioEn: "'Antara ibn Shaddad al-'Absi was a warrior-poet of the pre-Islamic (Jahili) era, born to an Arab father of the Banu 'Abs tribe and an Ethiopian slave-mother named Zabiba; he lived as a slave until his father freed him after his valor in battle. He became one of the most celebrated knights of the Arabs and an author of one of the Mu'allaqat, renowned for his poetry of chivalry and heroism and his chaste love for his cousin 'Abla. His Mu'allaqa, \"Have the poets left any spot unpatched,\" is counted among the masterpieces of Arabic verse, blending tender love-prelude with fierce self-praise.",
    humanStoryAr: "عشِق عنترة ابنة عمه عَبْلة عشقًا عفيفًا، لكن أصله المُستعبَد ولونه الأسود حالا دون زواجه منها، فظلّ يطلب يدها ويُكلَّف بمهور تعجيزية من الغزو والإبل، يخوض الحروب ليُثبت أنّ السيف لا اللون هو ميزان الرجال.",
    humanStoryEn: "'Antara loved his cousin 'Abla with a chaste devotion, but his enslaved origin and black skin barred their marriage; he kept seeking her hand while being set impossible bride-prices of raids and camels, waging war to prove that a man is measured by his sword, not his color.",
    themes: ["fakhr", "ghazal", "hamasa"],
    signaturePoemIds: ["muallaqat-antara", "antara-afat-al-diyar", "antara-la-yahmil-al-hiqd"],
  },
  {
    id: "zuhayr",
    slug: "zuhayr",
    nameAr: "زهير بن أبي سلمى",
    nameEn: "Zuhayr ibn Abi Sulma",
    eraId: "jahili",
    birthYear: 520,
    deathYear: 609,
    region: "نجد، جزيرة العرب — Najd, Arabian Peninsula",
    bioAr: "زهير بن أبي سلمى المزني (نحو 520 – 609م) شاعر جاهلي من قبيلة مُزَينة، نشأ في ديار غطفان بنجد، ويُلقَّب بـ«حكيم الشعراء» لما في شعره من حِكَم وأمثال سائرة. كان أبوه شاعراً وخاله شاعراً، ونبغ من بنيه كعب وبجير، وقد أدرك ابنه كعب الإسلام ومدح النبي صلى الله عليه وسلم. اشتهر بتنقيح شعره وتجويده حتى نُسبت إليه «الحوليّات» التي كان ينظمها في حول كامل.",
    bioEn: "Zuhayr ibn Abi Sulma al-Muzani (c. 520–609 CE) was a pre-Islamic poet of the Muzayna tribe who lived among the Ghatafan in Najd, and is nicknamed \"the wise man of the poets\" for the proverbial wisdom that fills his verse. He came from a family of poets—his father and maternal uncle composed verse, and his sons Kaʿb and Bujayr followed him—and his son Kaʿb later embraced Islam and praised the Prophet. He was famed for endlessly polishing his odes, so much so that his finest poems were called \"the year-long ones\" (al-hawliyyat) because he would labour over each for a full year.",
    humanStoryAr: "نظم زهير معلقته بعد أن مزّقت حربُ داحس والغبراء قبيلتَي عبس وذبيان أربعين عاماً، فمدح هرم بن سنان والحارث بن عوف اللذين حقَنا الدماء وحملا الدِّيات من مالهما؛ ويفتتحها بوقوفه على أطلال محبوبته أمّ أوفى بعد عشرين حِجّة، يكاد لا يعرف الديار من طول الفراق.",
    humanStoryEn: "Zuhayr composed his Muʿallaqa after the war of Dahis and al-Ghabra had torn the tribes of ʿAbs and Dhubyan apart for forty years, praising Harim ibn Sinan and al-Harith ibn ʿAwf, the two chiefs who stopped the bloodshed and paid the blood-money from their own wealth; he opens it standing over the ruined abode of his beloved Umm Awfa after twenty years, barely able to recognize the place after so long an absence.",
    themes: ["hikma", "ghazal"],
    signaturePoemIds: ["muallaqat-zuhayr", "zuhayr-saha-al-qalb", "zuhayr-liman-al-diyar"],
  },
  {
    id: "al-khansa",
    slug: "al-khansa",
    nameAr: "الخَنساء — تُماضِر بنت عمرو",
    nameEn: "Al-Khansa' (Tumadir bint 'Amr)",
    eraId: "jahili",
    birthYear: 575,
    deathYear: 645,
    region: "نجد، جزيرة العرب (بنو سُليم)",
    bioAr: "الخَنساء هي تُماضِر بنت عمرو بن الحارث بن الشَّريد السُّلَمية، أشهر شاعرة في تاريخ العرب وسيدة شعر الرثاء. عاشت معظم حياتها في الجاهلية ثم أدركت الإسلام وأسلمت ووفدت على النبي صلى الله عليه وسلم. أكثرُ شعرها وأجوده في رثاء أخويها صخر ومعاوية اللذين قُتلا، حتى صار اسمها مقروناً بالحزن والبكاء.",
    bioEn: "Al-Khansa' was Tumadir bint 'Amr ibn al-Harith ibn al-Sharid of the tribe of Sulaym, the most celebrated woman poet in Arab history and the supreme voice of the elegy (ritha'). She lived most of her life in the pre-Islamic era, then embraced Islam and came in delegation to the Prophet. The greatest and finest of her verse is the lament for her two slain brothers, Sakhr and Mu'awiyah, so that her name became bound forever to grief and weeping.",
    humanStoryAr: "قُتل أخوها معاوية، فحرّضت أخاها صخراً على الأخذ بثأره، فثأر له ثم مات متأثراً بجراحه، فبكته الخنساء حتى قيل إنها فقدت بصرها من كثرة الدمع. وفي الإسلام قدّمت أبناءها الأربعة إلى معركة القادسية فاستُشهدوا جميعاً، فقالت: «الحمد لله الذي شرّفني بقتلهم».",
    humanStoryEn: "When her brother Mu'awiyah was killed, she goaded her brother Sakhr into avenging him; Sakhr took the revenge but died of his wounds, and al-Khansa' wept for him until, it is said, she lost her sight from weeping. Under Islam she sent her four sons to the battle of al-Qadisiyya, where all were martyred, and she said: \"Praise be to God who honored me with their deaths.\"",
    themes: ["ritha"],
    signaturePoemIds: ["al-khansa-qasida", "al-khansa-a3ynayi-juda", "al-khansa-bakat-ayni"],
  },
  {
    id: "tarafa",
    slug: "tarafa",
    nameAr: "طَرَفة بن العَبد",
    nameEn: "Tarafa ibn al-'Abd",
    eraId: "jahili",
    birthYear: 543,
    deathYear: 569,
    region: "شرق جزيرة العرب (بكر بن وائل)",
    bioAr: "طَرَفة بن العَبد البَكري، أصغر أصحاب المعلّقات السبع وأنبغهم في فتوّته. عاش حياة لهوٍ ومجون ونظم معلّقته وهو دون الثلاثين، فجمع فيها بين وصف الناقة الفريد والحكمة الناضجة في العيش والموت، ويُعَدّ من أبرز شعراء الجاهلية رغم قِصَر عمره.",
    bioEn: "Tarafa ibn al-'Abd of the tribe of Bakr ibn Wa'il was the youngest of the seven Mu'allaqat poets and the most precocious. He lived a life of revelry and composed his great ode before he was thirty, joining an unrivalled description of his she-camel to a mature wisdom on life and death, and is reckoned among the foremost poets of the pre-Islamic age despite his short life.",
    humanStoryAr: "يُروى أنّ الملك عمرو بن هند نقم عليه فبعثه إلى عامله بهَجَر حاملاً صحيفةً يحسبها جائزةً وفيها أمرٌ سرّيٌّ بقتله، فحمل حتفه بيده ومات شابّاً لم يُكمل عقده الثالث.",
    humanStoryEn: "It is told that King 'Amr ibn Hind turned against him and sent him to his governor in Hajar bearing a sealed letter he took for a reward, but which secretly ordered his death — so he carried his own doom in his hand and died young, before completing his thirtieth year.",
    themes: ["ghazal", "hikma", "fakhr"],
    signaturePoemIds: ["muallaqat-tarafa", "tarafa-likhawla", "tarafa-sa-ilu"],
  },
  {
    id: "labid",
    slug: "labid",
    nameAr: "لَبيد بن رَبيعة",
    nameEn: "Labid ibn Rabi'a",
    eraId: "jahili",
    birthYear: 560,
    deathYear: 661,
    region: "نجد (بنو عامر بن صعصعة)",
    bioAr: "لَبيد بن رَبيعة العامري، آخر أصحاب المعلّقات عهداً، شاعرٌ فارسٌ من بني عامر بن صعصعة. أدرك الإسلام فأسلم وحسن إسلامه، ومعلّقته من أرقّ ما قيل في وصف الأطلال والظعينة وتقلّب الدهر، تختم بالقناعة والتسليم بقسمة الله.",
    bioEn: "Labid ibn Rabi'a of the tribe of 'Amir ibn Sa'sa'a was the last in time of the Mu'allaqat poets, a knight as well as a poet. He lived to see Islam and embraced it well; his ode is among the tenderest ever spoken on the ruined campsite, the departing women, and the turning of fate, closing in contentment and submission to God's apportioning.",
    humanStoryAr: "يُروى أنّه ترك الشعر بعد إسلامه وقال: «أبدلني الله به سُوَرَ البقرة وآل عمران»، وعُمّر طويلاً حتى جاوز المئة، ومات بالكوفة في خلافة معاوية، فكان جسراً حيّاً بين شعر الجاهلية وهدي الإسلام.",
    humanStoryEn: "It is said that he gave up poetry after his conversion, declaring, 'God has given me the chapters of the Cow and of 'Imran's House in its place.' He lived past a hundred years and died at Kufa in the caliphate of Mu'awiya — a living bridge between the poetry of the pre-Islamic age and the guidance of Islam.",
    themes: ["ghazal", "hikma", "fakhr"],
    signaturePoemIds: ["muallaqat-labid", "labid-ala-tasalan", "labid-balina"],
  },
  {
    id: "amr-ibn-kulthum",
    slug: "amr-ibn-kulthum",
    nameAr: "عَمرو بن كُلثوم",
    nameEn: "'Amr ibn Kulthum",
    eraId: "jahili",
    birthYear: 526,
    deathYear: 584,
    region: "الجزيرة الفراتية (بنو تغلب)",
    bioAr: "عَمرو بن كُلثوم التَّغلِبي، سيّد قومه وفارسهم، ساد وهو فتى. صاحب معلّقةٍ في الفخر بتغلب وأيّامها وعزّتها، مطلعها خمريٌّ شهير، حتى قيل إنّ بني تغلب لهَوا بها زماناً يردّدونها فخراً.",
    bioEn: "'Amr ibn Kulthum of the tribe of Taghlib was the lord and knight of his people, rising to chieftaincy while still a youth. He is the author of a Mu'allaqa boasting of Taghlib's battle-days and might, opening with a famous wine-prelude; it is said the Banu Taghlib were so taken with it that they recited it in pride for generations.",
    humanStoryAr: "لمّا أراد الملك عمرو بن هند إذلال أمّه ليلى بنت المهلهل، صاحت: «واذُلّاه يا لتغلب!»، فوثب عمرو على الملك فقتله بسيفه في مجلسه، فصارت تلك الفعلة مفخرةً لبني تغلب خلّدها في معلّقته.",
    humanStoryEn: "When King 'Amr ibn Hind sought to humiliate his mother Layla bint al-Muhalhil, she cried out, 'O the shame, O Taghlib!' — and 'Amr leapt upon the king and slew him with his sword in his own hall. The deed became a glory of the Banu Taghlib, which he immortalized in his ode.",
    themes: ["fakhr", "hamasa"],
    signaturePoemIds: ["muallaqat-amr-ibn-kulthum"],
  },
  {
    id: "al-harith",
    slug: "al-harith",
    nameAr: "الحارث بن حِلِّزة",
    nameEn: "Al-Harith ibn Hilliza",
    eraId: "jahili",
    birthYear: 500,
    deathYear: 570,
    region: "الجزيرة الفراتية (بكر بن وائل، بنو يشكر)",
    bioAr: "الحارث بن حِلِّزة اليَشكُري، خطيب بكرٍ وشاعرها، وصاحب سابعة المعلّقات. شاعرٌ مُفلِقٌ من شعراء القرن السادس الميلادي، اشتُهر بمعلّقته في الاحتجاج لقومه والمفاخرة بين يدي الملوك.",
    bioEn: "Al-Harith ibn Hilliza of the tribe of Yashkur (Bakr ibn Wa'il) was the orator and poet of Bakr and author of the seventh of the Mu'allaqat. A masterly poet of the sixth century CE, he is famed for his ode of pleading and pride delivered before kings.",
    humanStoryAr: "يُروى أنّه ارتجل معلّقته بين يدي الملك عمرو بن هند مدافعاً عن بكرٍ في خصومتها مع تغلب، وكان به بَرَصٌ فأُقيمت دونه ستورٌ وأُجلِس بعيداً؛ فلمّا سمع الملك شعره أمر برفع الستور وأدناه منه إعجاباً به.",
    humanStoryEn: "It is told that he improvised his ode before King 'Amr ibn Hind in defence of Bakr against Taghlib. He was afflicted with leprosy, so curtains were hung between him and the king and he was seated far off; but when the king heard his verse he ordered the curtains drawn back and brought him near in admiration.",
    themes: ["fakhr", "hikma"],
    signaturePoemIds: ["muallaqat-al-harith"],
  },
  {
    id: "al-nabigha",
    slug: "al-nabigha",
    nameAr: "النابغة الذُّبياني",
    nameEn: "Al-Nabigha al-Dhubyani",
    eraId: "jahili",
    birthYear: 535,
    deathYear: 604,
    region: "نجد والحيرة والشام (بنو ذبيان)",
    bioAr: "النابغة الذُّبياني، واسمه زياد بن معاوية، من فحول شعراء الجاهلية، تُعَدّ داليّته في المعلّقات عند كثيرٍ من الرواة. كان شاعر بلاط المناذرة والغساسنة، وتُضرب به الأمثال في الاعتذار، وكانت تُضرب له قبّةٌ من أَدَمٍ بسوق عُكاظ يُحتكَم إلى ذوقه في الشعر.",
    bioEn: "Al-Nabigha al-Dhubyani, whose name was Ziyad ibn Mu'awiya, was a master of the pre-Islamic poets, his dal-rhymed ode counted by many among the Mu'allaqat. A court poet of the Lakhmids and Ghassanids, he is proverbial for the art of apology; a dome of red leather was raised for him at the fair of 'Ukaz, where poets submitted their verse to his judgement.",
    humanStoryAr: "وقعت بينه وبين النعمان بن المنذر جفوةٌ بعد أن سعى به الوشاة، فهرب إلى الغساسنة، ثم نظم أرقّ قصائد الاعتذار يستعطف بها النعمان حتى رضي عنه وأعاده إلى مكانته، فصار إمام المعتذرين في الشعر العربي.",
    humanStoryEn: "A breach opened between him and al-Nu'man ibn al-Mundhir after slanderers turned the king against him, and he fled to the Ghassanids; then he composed the tenderest of apology-odes to win al-Nu'man back, until the king relented and restored him to favour — making him the master of the poetry of apology.",
    themes: ["ghazal", "fakhr", "hikma"],
    signaturePoemIds: ["muallaqat-al-nabigha", "al-nabigha-amin-al-miyya", "al-nabigha-kilini-lihamm"],
  },
  {
    id: "al-shanfara",
    slug: "al-shanfara",
    nameAr: "الشَّنفَرى",
    nameEn: "Al-Shanfara",
    eraId: "jahili",
    birthYear: 480,
    deathYear: 525,
    region: "جنوب جزيرة العرب (الأزد)",
    bioAr: "الشَّنفَرى الأَزدي، أحد الشعراء الصعاليك وأشهر العَدّائين في الجاهلية، خلعته قبيلته فآثر صحبة الوحش على صحبة الناس. صاحب «لاميّة العرب» التي يصوّر فيها عزّة النفس والاستغناء عن القوم الظالمين، وهي من أعجب ما قيل في الإباء وأدب الصعلكة.",
    bioEn: "Al-Shanfara of Azd was one of the brigand-poets (sa'alik) and the most famous of the desert runners of the pre-Islamic age; disowned by his tribe, he chose the company of wild beasts over that of men. He is the author of the 'Lamiyyat al-'Arab,' in which he portrays pride of soul and self-sufficiency away from an unjust people — among the most remarkable verse ever composed on disdain and the brigand's code.",
    humanStoryAr: "عاش ثائراً على قومه، يُغير وحده ويقتات من الصيد، وقد آلى أن يثأر لما لقي من ظلم؛ وتبقى لاميّته نشيد كلّ نفسٍ أبيّةٍ تأبى الضيم وتؤثر الوحدة على ذلّ المجالس.",
    humanStoryEn: "He lived in revolt against his people, raiding alone and living by the hunt, and swore vengeance for the wrongs he had suffered; his Lamiyya remains the anthem of every proud soul that refuses to be wronged and prefers solitude to a seat among the humbled.",
    themes: ["fakhr", "hamasa", "hikma"],
    signaturePoemIds: ["al-shanfara-lamiyya", "al-shanfara-inna-bilshib", "al-shanfara-ala-umm-amr"],
  },
  {
    id: "jarir",
    slug: "jarir",
    nameAr: "جرير بن عطية",
    nameEn: "Jarir ibn Atiyya",
    eraId: "umawi",
    birthYear: 653,
    deathYear: 728,
    region: "نجد / البصرة (قبيلة تميم)",
    bioAr: "جرير بن عطية الخَطَفي التميمي، من بني يربوع، أحد أعظم شعراء العصر الأموي وأحد أركان النقائض الثلاثة مع الفرزدق والأخطل. وُلد ونشأ في بادية نجد ثم استقر بالبصرة، وبرع في الهجاء والمديح والغزل والرثاء، حتى قيل إنه هَجا نحو ثمانين شاعرًا ولم يصمد أمامه إلا الفرزدق والأخطل. اشتهر بسهولة لفظه ورقة غزله، وامتدت مساجلاته الشعرية قرابة أربعين عامًا فصارت من أشهر المعارك الأدبية في تاريخ العربية.",
    bioEn: "Jarir ibn Atiyya al-Khatafi al-Tamimi, of the Banu Yarbu', was one of the greatest poets of the Umayyad era and one of the three masters of the naqa'id (poetic flytings) alongside al-Farazdaq and al-Akhtal. Born and raised in the Najd desert before settling in Basra, he excelled in satire, panegyric, love poetry, and elegy, and is said to have lampooned some eighty poets, with only al-Farazdaq and al-Akhtal able to withstand him. Famed for the ease of his diction and the tenderness of his ghazal, his poetic duels stretched across roughly forty years and became among the most celebrated literary feuds in Arabic history.",
    humanStoryAr: "عاش جرير حياته في حربٍ شعريةٍ ضروسٍ مع غريمه الفرزدق دامت أربعين عامًا حتى ماتا متقاربين، لكنه خلف وراء هذا الهجاء المرّ غزلًا رقيقًا يفيض حنينًا، كأن بيته الخالد \"إن العيون التي في طرفها حور\" شكوى عاشقٍ صرعته نظرةٌ من أضعف خلق الله.",
    humanStoryEn: "Jarir spent his life locked in a ferocious forty-year poetic war with his rival al-Farazdaq, the two dying not long apart, yet behind that bitter satire he left a tender, yearning ghazal — as if his immortal line \"Indeed the eyes whose glance holds languor\" were the lament of a lover felled by a single look from the frailest of God's creatures.",
    themes: ["ghazal", "hija", "fakhr"],
    signaturePoemIds: ["jarir-qasida", "jarir-atashu", "jarir-lawla-alhaya"],
  },
  {
    id: "al-farazdaq",
    slug: "al-farazdaq",
    nameAr: "الفرزدق — همّام بن غالب",
    nameEn: "Al-Farazdaq (Hammam ibn Ghalib)",
    eraId: "umawi",
    birthYear: 641,
    deathYear: 728,
    region: "البصرة، العراق (بنو تميم)",
    bioAr: "همّام بن غالب بن صعصعة الدارمي التميمي، المعروف بالفرزدق، شاعر أموي وُلد قرب البصرة سنة 20 هـ تقريبًا وتوفي بها سنة 110 هـ. يُعدّ من أعظم شعراء العصر الأموي وأحد أركان الفخر والهجاء، حتى قيل: لولا شعر الفرزدق لذهب ثلث لغة العرب. اشتهر بنقائضه الطويلة مع غريمه جرير، وبقصائده في الفخر بقومه بني تميم.",
    bioEn: "Hammam ibn Ghalib al-Darimi al-Tamimi, known as al-Farazdaq, was an Umayyad poet born near Basra around 20 AH (c. 641 CE) and died there in 110 AH (728 CE). He is counted among the greatest poets of the Umayyad age and a master of fakhr (self-praise) and hija (invective); it was said that \"were it not for al-Farazdaq's poetry, a third of the Arabic language would be lost.\" He is most famous for his lifelong poetic duels (naqa'id) with his rival Jarir and for his proud odes celebrating his tribe, Banu Tamim.",
    humanStoryAr: "قضى الفرزدق عمره في صراع شعري عنيف مع غريمه جرير دام نحو خمسين عامًا، يتبادلان النقائض في الفخر والهجاء أمام العرب جميعًا، فكان عداؤهما من أشهر الخصومات الأدبية في تاريخ العربية، ولم يهدأ إلا بموت أحدهما.",
    humanStoryEn: "Al-Farazdaq spent his life locked in a ferocious poetic feud with his rival Jarir that lasted roughly fifty years, the two trading boasts and invectives before all the Arabs; their enmity became one of the most famous literary rivalries in Arabic history, ending only with the death of one of them.",
    themes: ["fakhr", "hija"],
    signaturePoemIds: ["al-farazdaq-qasida", "al-farazdaq-zayn-al-abidin", "al-farazdaq-azafta"],
  },
  {
    id: "al-mutanabbi",
    slug: "al-mutanabbi",
    nameAr: "أبو الطيب المتنبي",
    nameEn: "Abu al-Tayyib al-Mutanabbi",
    eraId: "abbasi",
    birthYear: 915,
    deathYear: 965,
    region: "الكوفة، العراق",
    bioAr: "أبو الطيب أحمد بن الحسين المتنبي (303-354 هـ / 915-965 م)، من أعظم شعراء العربية على الإطلاق، وُلد بالكوفة ونشأ بها ثم تنقّل بين الشام والعراق وفارس ومصر. اشتهر بمدائحه لسيف الدولة الحمداني في حلب، حيث بلغ ذروة مجده الشعري، وامتاز شعره بالحكمة وعزّة النفس والفخر الشديد بنفسه وبالعرب. قُتل عائدًا إلى العراق سنة 354 هـ، وبقي ديوانه من أكثر دواوين الشعر العربي شرحًا ودراسةً وتداولًا.",
    bioEn: "Abu al-Tayyib Ahmad ibn al-Husayn al-Mutanabbi (915-965 CE) is widely regarded as the greatest of all Arabic poets. Born in Kufa, he wandered across the Levant, Iraq, Persia, and Egypt, reaching the summit of his fame in the court of Sayf al-Dawla al-Hamdani at Aleppo. His verse is celebrated for its wisdom, towering self-pride, and martial grandeur; he was killed on the road back to Iraq in 965, and his Diwan remains among the most studied and quoted in the entire Arabic tradition.",
    humanStoryAr: "عاش المتنبي حياة طموح جامح وكبرياء لا يلين، فطمح إلى الإمارة وعاش ربيع عمره في كنف سيف الدولة قبل أن تفسد العلاقة بسبب الحساد والوشاة، فرحل عنه عاتبًا. وقد قُتل في نهاية المطاف لأنه أبى الفرار من المعركة حين عُيّر ببيته «الخيلُ والليلُ والبيداءُ تعرفني»، فمات وفيًّا لكبريائه.",
    humanStoryEn: "Al-Mutanabbi lived a life of unbending pride and a craving for power, spending his prime in Sayf al-Dawla's court until envy and slander poisoned the bond and drove him away in bitter reproach. In the end he was killed because he refused to flee a fight when taunted with his own verse \"The horse, the night, and the desert know me\" — dying true to the pride he had spent a lifetime singing.",
    themes: ["fakhr", "hikma", "hamasa"],
    signaturePoemIds: ["al-mutanabbi-qasida", "al-mutanabbi-waharra", "al-mutanabbi-iza-ghamarta"],
  },
  {
    id: "abu-nuwas",
    slug: "abu-nuwas",
    nameAr: "أبو نُواس — الحَسَن بن هانئ",
    nameEn: "Abu Nuwas (al-Hasan ibn Hani)",
    eraId: "abbasi",
    birthYear: 756,
    deathYear: 814,
    region: "العراق (البصرة وبغداد)",
    bioAr: "أبو نُواس الحَسَن بن هانئ الحَكَمي (نحو 756 - 814م)، من أبرز شعراء العصر العباسي ورائد الشِّعر المُحدَث. وُلد في الأهواز ونشأ بالبصرة حيث حفظ القرآن، ثم انتقل إلى بغداد فاتصل بالخليفة هارون الرشيد ثم الأمين. اشتهر بخمرياته ومجونه وحضور بديهته، كما له زهديات وتوبيات في أواخر حياته يتضرّع فيها إلى الله ويرجو عفوه.",
    bioEn: "Abu Nuwas, al-Hasan ibn Hani al-Hakami (c. 756–814 CE), was a leading poet of the Abbasid era and the foremost figure of the \"modern\" (muhdath) style. Born in Ahvaz and raised in Basra, where he memorized the Qur'an, he later moved to Baghdad and attached himself to the caliphs Harun al-Rashid and al-Amin. Famous for his wine poetry (khamriyyat), wit, and libertinism, he also composed ascetic and penitential verses in his later years, pleading for God's mercy and forgiveness.",
    humanStoryAr: "عاش أبو نواس حياة لهوٍ وخمرٍ ومجون، ثم أدركه الندم في أواخر أيامه؛ ويُروى أنه لمّا مات وُجدت تحت رأسه رقعة بخط يده مكتوب فيها هذه الأبيات في التضرّع والتوبة ورجاء عفو الله.",
    humanStoryEn: "Abu Nuwas lived a life of revelry, wine, and dissipation, then remorse overtook him in his final days; it is said that when he died, a scrap of paper in his own hand was found beneath his head bearing these verses of supplication, repentance, and hope in God's forgiveness.",
    themes: ["hikma", "ritha"],
    signaturePoemIds: ["abu-nuwas-qasida", "abu-nuwas-da-annaka", "abu-nuwas-ala-fasqini"],
  },
  {
    id: "al-maarri",
    slug: "al-maarri",
    nameAr: "أبو العلاء المعري",
    nameEn: "Abu al-ʿAlaʾ al-Maʿarri",
    eraId: "abbasi",
    birthYear: 973,
    deathYear: 1057,
    region: "معرة النعمان، بلاد الشام (Maʿarrat al-Nuʿman, Syria)",
    bioAr: "أبو العلاء أحمد بن عبد الله بن سليمان التنوخي المعري (363–449هـ / 973–1057م) شاعرٌ وفيلسوفٌ ولغويٌّ من عصر الدولة العباسية، وُلد وتُوفّي في معرة النعمان بالشام. كُفّ بصره طفلاً إثر إصابته بالجدري، فلُقّب بـ\"رهين المحبسين\" (العمى ولزومه بيته). من أشهر دواوينه «سقط الزند» و«اللزوميات» (لزوم ما لا يلزم)، ورسالته الفلسفية «رسالة الغفران»، وقد اشتهر بنزعته العقلانية التشاؤمية وتأملاته في الحياة والموت والدين.",
    bioEn: "Abu al-ʿAlaʾ Ahmad ibn ʿAbd Allah al-Tanukhi al-Maʿarri (363–449 AH / 973–1057 CE) was a poet, philosopher, and grammarian of the Abbasid era, born and died in Maʿarrat al-Nuʿman in Syria. Blinded by smallpox as a small child, he came to be called \"the prisoner of two prisons\" (his blindness and his self-imposed seclusion at home). His most famous works are the diwans Saqt al-Zand and al-Luzumiyyat, and the prose Risalat al-Ghufran (Epistle of Forgiveness); he is renowned for his rationalist, pessimistic outlook and his meditations on life, death, and religion.",
    humanStoryAr: "عاش المعري زاهداً معتزلاً عن الناس، نباتيّاً لم يتزوّج ولم يُنجب، وأوصى أن يُكتب على قبره: «هذا جناه أبي عليّ وما جنيتُ على أحد»، احتجاجاً على ما رأى أنه ظلمُ إيجاد الأبناء في عالمٍ مليء بالألم.",
    humanStoryEn: "Al-Maʿarri lived as an ascetic recluse, a vegetarian who never married or had children, and asked that his epitaph read: \"This wrong was done to me by my father, but I wronged no one,\" a protest against what he saw as the injustice of bringing children into a world full of suffering.",
    themes: ["hikma"],
    signaturePoemIds: ["al-maarri-qasida", "al-maarri-ala-fi-sabil", "al-maarri-ya-sahir"],
  },
  {
    id: "ibn-zaydun",
    slug: "ibn-zaydun",
    nameAr: "ابن زيدون",
    nameEn: "Ibn Zaydun",
    eraId: "andalusi",
    birthYear: 1003,
    deathYear: 1071,
    region: "الأندلس (قرطبة)",
    bioAr: "أبو الوليد أحمد بن عبد الله بن أحمد بن غالب المخزومي، المعروف بابن زيدون (394–463 هـ / 1003–1070 م)، شاعر ووزير وكاتب أندلسي من قرطبة، يُعدّ من أعظم شعراء الأندلس وأشهر شعراء الغزل في العربية حتى لُقّب بـ«بحتري المغرب». عاش في زمن ملوك الطوائف وتنقّل بين بلاط بني جهور في قرطبة وبني عبّاد في إشبيلية، وامتاز شعره برقّة العاطفة وجزالة اللفظ ووصف الطبيعة. وهو صاحب النونية الخالدة التي نظمها في حبيبته ولّادة بنت المستكفي.",
    bioEn: "Abu al-Walid Ahmad ibn Abdullah al-Makhzumi, known as Ibn Zaydun (1003–1070 CE), was an Andalusian poet, vizier, and prose stylist from Cordoba, regarded as one of the greatest poets of al-Andalus and the foremost master of love poetry (ghazal) in Arabic, earning him the title \"the Buhturi of the West.\" He lived during the era of the Party Kings (muluk al-tawa'if), serving in the courts of the Banu Jahwar of Cordoba and the Banu Abbad of Seville, and his verse is celebrated for its tenderness, polished diction, and descriptions of nature. He is the author of the immortal Nuniyya composed for his beloved, the princess-poet Wallada bint al-Mustakfi.",
    humanStoryAr: "أحبّ ابن زيدون الأميرة الشاعرة ولّادة بنت المستكفي حبًّا عاصفًا، لكنّ الوشاة ومنافسه الوزير ابن عبدوس فرّقوا بينهما، فسُجن ثم نفي عن قرطبة، فنظم نونيته يذوب أسىً على فراقها وذكرى أيامهما الصافية.",
    humanStoryEn: "Ibn Zaydun fell passionately in love with the princess-poet Wallada bint al-Mustakfi, but slanderers and his rival, the vizier Ibn Abdus, drove them apart; imprisoned and then exiled from Cordoba, he poured his anguish at their separation and the memory of their pure days together into his celebrated Nuniyya.",
    themes: ["ghazal"],
    signaturePoemIds: ["ibn-zaydun-qasida", "ibn-zaydun-zahraa", "ibn-zaydun-mata-abuthuk"],
  },
  {
    id: "shawqi",
    slug: "shawqi",
    nameAr: "أَحْمَد شَوْقِي",
    nameEn: "Ahmad Shawqi",
    eraId: "hadith",
    birthYear: 1868,
    deathYear: 1932,
    region: "Egypt (Cairo)",
    bioAr: "أحمد شوقي (1868–1932) شاعر وكاتب مسرحي مصري، أشهر شعراء العربية في العصر الحديث، لُقّب بـ«أمير الشعراء» بعد أن بايعه شعراء العرب أميراً عام 1927. وُلد في القاهرة لأب من أصل كردي وأم من أصل تركي يوناني، ونشأ في كنف بلاط الخديوي إسماعيل، ودرس الحقوق في فرنسا. يُعَدّ رائد المسرح الشعري العربي، ومن أبرز أعماله القصيدة الهمزية «وُلِدَ الهُدى» في مدح النبي ﷺ ونهج البردة معارضةً لبردة البوصيري.",
    bioEn: "Ahmad Shawqi (1868–1932) was an Egyptian poet and playwright, the most celebrated Arabic poet of the modern era, acclaimed as \"Prince of Poets\" (Amir al-Shu'ara') when the Arab poets pledged the title to him in 1927. Born in Cairo to a father of Kurdish descent and a mother of Turkish-Greek origin, he was raised within the court of Khedive Ismail and studied law in France. He pioneered Arabic verse drama, and among his most famous works is the hamziyya \"Wulida al-Huda\" in praise of the Prophet, alongside \"Nahj al-Burda,\" composed in emulation of al-Busiri's Burda.",
    humanStoryAr: "نفاه الاحتلال البريطاني إلى إسبانيا سنة 1915 بسبب مواقفه الوطنية المناهضة، فعاش غربةً مريرة بين ربوع الأندلس يحنّ إلى وطنه ونيله، ومن وحي ذلك المنفى استلهم بعضاً من أصدق شعره في الحنين إلى مصر قبل أن يعود إليها سنة 1920.",
    humanStoryEn: "The British occupation exiled him to Spain in 1915 for his defiant patriotic stance, and he lived a bitter estrangement among the ruins of Andalusia, aching for his homeland and the Nile; that exile inspired some of his most heartfelt verse of longing for Egypt before he was permitted to return in 1920.",
    themes: ["hikma", "fakhr"],
    signaturePoemIds: ["shawqi-qasida", "shawqi-nahj-al-burda", "shawqi-mudnaka"],
  },
  {
    id: "tarafa",
    slug: "tarafa",
    nameAr: "طَرَفة بن العبد",
    nameEn: "Ṭarafa ibn al-ʿAbd",
    eraId: "jahili",
    birthYear: 543,
    deathYear: 569,
    region: "إقليم البحرين التاريخي (شمال شرق الجزيرة العربية)",
    bioAr: "طَرَفة بن العبد البكري شاعرٌ جاهليٌّ من الطبقة الأولى وصاحب إحدى المعلقات، من بني بكر بن وائل في إقليم البحرين، نشأ في بيت شعرٍ عريق فجدّه وأبوه وأخواله من الشعراء. اشتهر بمعلقته الدالية ذات النزعة الإنسانية والتأملات في الموت والحياة، ويُعدّ من أوائل من نظموا الشعر الفلسفي في الجاهلية رغم قصر عمره.",
    bioEn: "Ṭarafa ibn al-ʿAbd al-Bakrī was a first-rank pre-Islamic poet and author of one of the Muʿallaqāt, from the tribe of Bakr ibn Wāʾil in the historical region of Bahrain. Born into a literary family (his grandfather, father, and maternal uncles were poets), he is celebrated for his dāl-rhymed Muʿallaqa, notable for its humanistic spirit and its meditations on death and the fleeting pleasures of life. Though he died very young, he secured lasting fame.",
    humanStoryAr: "عاش طرفة طفولةً مضطربة؛ فقد أباه صغيراً فاستأثر أعمامه بميراثه وأهملوه، فألقى بنفسه في اللهو والشراب والترحال حتى تبرّأت منه عشيرته ونفته. عُرف بحدّة لسانه وهجائه. اتصل بعمرو بن هند ملك الحيرة منادماً، لكن هجاءه أثار حنق الملك، فبعثه برسالةٍ مختومة إلى عامله على البحرين تأمر بقتله — فقُتل وهو في نحو السادسة والعشرين، فصار مثلاً في «رسالة المتلمّس» وفي موت الشاب نديّ الموهبة.",
    humanStoryEn: "Ṭarafa's youth was turbulent: his father died when he was young and his uncles seized his inheritance, so he plunged into wine, pleasure, and wandering until his own clan disowned and exiled him. He was famous for his sharp tongue and satire (hijāʾ). He became a boon-companion to ʿAmr ibn Hind, king of al-Ḥīra, but his lampoons angered the king, who sent him with a sealed letter to his governor in Bahrain ordering his execution. He was killed around the age of twenty-six — the proverbial fate of a brilliant young poet betrayed by his own verse.",
    themes: [
      "fakhr",
      "hikma",
      "ghazal",
      "hija",
      "hamasa"
    ],
    signaturePoemIds: ["muallaqat-tarafa", "tarafa-likhawla", "tarafa-sa-ilu"],
  },
  {
    id: "labid",
    slug: "labid",
    nameAr: "لبيد بن ربيعة العامري",
    nameEn: "Labīd ibn Rabīʿa al-ʿĀmirī",
    eraId: "jahili",
    birthYear: 560,
    deathYear: 661,
    region: "نجد (بلاد بني عامر بن صعصعة من هوازن)",
    bioAr: "لبيد بن ربيعة بن مالك العامري، من بني عامر بن صعصعة من هوازن، شاعر مخضرم أدرك الجاهلية والإسلام وعُدّ من المعمَّرين. وُلد في نجد ونشأ فارساً شريفاً في قومه، وله إحدى المعلقات السبع المشهورة، ثم أسلم وسكن الكوفة حتى توفي بها في خلافة معاوية نحو سنة 41 للهجرة.",
    bioEn: "Labīd ibn Rabīʿa ibn Mālik al-ʿĀmirī, of Banū ʿĀmir ibn Ṣaʿṣaʿa (Hawāzin), was a mukhaḍram poet who lived through both the pre-Islamic and Islamic eras and was reckoned among the long-lived (muʿammarūn). Born in the highlands of Najd, he rose as a noble warrior-poet of his tribe and composed one of the famed Seven Muʿallaqāt; he later embraced Islam, settled in Kūfa, and died there around 41 AH (c. 661 CE).",
    humanStoryAr: "يُروى أن لبيداً لما أسلم هجر الشعر أو كاد، وقال إن الله أبدله بالقرآن عمّا كان ينظمه، فلم يُنسب إليه في الإسلام إلا النزر اليسير. وقد عاش عمراً طويلاً تجاوز فيه القرن، حتى صار مثلاً في طول العمر، يردّد حكمته التي ختم بها أيامه: أن المرء لا يملك إلا ما قسم له، وأن المنايا لا تطيش سهامها.",
    humanStoryEn: "It is said that when Labīd embraced Islam he gave up poetry almost entirely, declaring that God had granted him the Qurʾān in place of the verse he once composed; scarcely a line is attributed to him from his Muslim years. He lived an extraordinarily long life of well over a century, becoming a byword for longevity, carrying into old age the wisdom that closes his ode: that a man possesses only what is allotted to him, and that the arrows of fate never miss their mark.",
    themes: [
      "fakhr",
      "ritha",
      "hikma",
      "ghazal",
      "hamasa"
    ],
    signaturePoemIds: ["muallaqat-labid", "labid-ala-tasalan", "labid-balina"],
  },
  {
    id: "amr-ibn-kulthum",
    slug: "amr-ibn-kulthum",
    nameAr: "عَمْرو بن كُلْثوم",
    nameEn: "ʿAmr ibn Kulthūm",
    eraId: "jahili",
    birthYear: 526,
    deathYear: 600,
    region: "الجزيرة الفراتية وبلاد ربيعة (شمال شرق الجزيرة العربية والعراق والشام)",
    bioAr: "عَمْرو بن كُلْثوم بن مالك بن عَتّاب التَّغْلِبي، من بني تغلب من ربيعة بن نزار، وأمّه لَيْلى بنت المُهَلْهِل بن ربيعة. شاعر جاهلي فحل وسيّد قبيلته بني تغلب، ساد قومه وهو فتى في نحو الخامسة عشرة من عمره، وعُرف بالعزّة والإباء والفخر بالحسب. عاش عمراً طويلاً، وضُرب به المثل في المنعة. صاحب إحدى المعلقات السبع المشهورة، وهي نونيّة على بحر الوافر تُعَدّ من أبلغ شعر الفخر والحماسة في الجاهلية.",
    bioEn: "ʿAmr ibn Kulthūm ibn Mālik ibn ʿAttāb al-Taghlibī was a major pre-Islamic (Jāhilī) poet and chief of the tribe of Taghlib, a branch of Rabīʿa ibn Nizār. His mother was Laylā, daughter of the warrior-poet al-Muhalhil. He became lord (sayyid) of his tribe while still a youth, reportedly around the age of fifteen, and was renowned for his pride, defiance and fierce tribal honor. He lived to a great age. He is the author of one of the seven Muʿallaqāt, a nūniyya in the wāfir meter that ranks among the finest verse of fakhr (boasting) and martial glory in the pre-Islamic canon.",
    humanStoryAr: "تُروى قصته مع عَمْرو بن هِنْد، ملك الحيرة اللخمي، الذي أراد أن يُذِلّ بني تغلب فدعا عَمْراً وأمَّه لَيْلى، وأمر أمَّه هنداً أن تستخدم لَيْلى في مناولة الطعام؛ فلمّا استغاثت لَيْلى بابنها صائحةً «وا ذُلّاه يا لَتَغْلِب»، ثار عَمْرو فاجتزّ سيفاً معلّقاً في القبّة وضرب به الملك فقتله، ثمّ خرج بقومه. وقد قال معلّقته فخراً ببني تغلب وتعديداً لأمجادهم ومنعتهم، حتّى رُوي أنّ بني تغلب أُولِعوا بإنشادها زماناً طويلاً. (لاحظ أنّ بعض المؤرّخين، كطه حسين، شكّكوا في تفاصيل هذه الرواية.)",
    humanStoryEn: "His most famous story concerns ʿAmr ibn Hind, the Lakhmid king of al-Ḥīra, who sought to humiliate the Taghlib. He invited ʿAmr and his mother Laylā, and arranged for his own mother Hind to make Laylā serve her. When Laylā cried out to her son — \"O the shame, O Taghlib!\" — ʿAmr seized a sword hanging in the king's pavilion and struck him dead, then escaped with his people. He composed his Muʿallaqa as a boast (fakhr) glorifying the Taghlib, their deeds and their invincibility; it is said the tribe recited it for generations. (Some modern historians, such as Ṭāhā Ḥusayn, have questioned the historicity of this account.)",
    themes: [
      "fakhr",
      "hamasa",
      "ghazal",
      "hikma"
    ],
    signaturePoemIds: ["muallaqat-amr-ibn-kulthum"],
  },
  {
    id: "al-harith",
    slug: "al-harith",
    nameAr: "الحارث بن حِلِّزة اليشكري",
    nameEn: "al-Hārith ibn Hilliza al-Yashkurī",
    eraId: "jahili",
    deathYear: 570,
    region: "بلاد بكر بن وائل في أطراف العراق (تخوم الحيرة)",
    bioAr: "الحارث بن حِلِّزة بن مكروه اليشكري، شاعر جاهلي من بني يشكر بن بكر بن وائل، من فحول شعراء العصر الجاهلي وأصحاب المعلّقات. عاش في أطراف العراق على تخوم مملكة الحِيرة اللخمية، ولم يصلنا من شعره إلا القليل، وعلى رأسه معلّقته الهمزية «آذَنَتنا بِبَينِها أَسماءُ» التي رفعت مكانته بين الشعراء. اشتُهر بالفخر بقومه حتى ضُرب به المثل، وتوفي نحو سنة 570م.",
    bioEn: "Al-Hārith ibn Hilliza ibn Makrūh al-Yashkurī was a pre-Islamic (Jāhilī) poet of the Banū Yashkur of Bakr ibn Wāʾil, counted among the masters of the age and the authors of the Muʿallaqāt. He lived on the marches of lower Iraq near the Lakhmid kingdom of al-Hīra. Little of his verse survives apart from his hamza-rhymed Muʿallaqa, \"Ādhanatnā bi-baynihā Asmāʾu,\" which secured his rank among the great poets. He died around 570 CE.",
    humanStoryAr: "تروي الأخبار أن الحارث كان شيخًا كبيرًا قد أصابه البَرَص حين وقع النزاع بين بكر وتغلب أمام الملك اللخمي عمرو بن هند بالحِيرة. فلما أنشد عمرو بن كلثوم معلّقته منافحًا عن تغلب، انتدب الحارث ليردّ عن بكر، فأنشد معلّقته ارتجالًا من وراء سبعة ستور وهو متّكئ على قوسه — إذ كان الملك يكره أن يراه لمرضه. فلما سمع الملك بلاغته أُعجب به إعجابًا شديدًا، فأمر برفع الستور واحدًا بعد واحد حتى أدناه منه وأجلسه إلى جانبه، وقضى لبكر على تغلب. وهي المعلّقة النظيرة لمعلّقة عمرو بن كلثوم في تلك الخصومة.",
    humanStoryEn: "Tradition holds that al-Hārith was already an old man, afflicted with leprosy, when the feud between Bakr and Taghlib was brought before the Lakhmid king ʿAmr ibn Hind at al-Hīra. After ʿAmr ibn Kulthūm recited his ode championing Taghlib, al-Hārith rose to answer for Bakr, improvising his Muʿallaqa from behind seven curtains while leaning on his bow — for the king would not look upon him because of his disease. So moved was the king by its eloquence that he had the curtains lifted one by one until he drew the poet near and seated him at his side, ruling in favor of Bakr. It is the companion ode to that of ʿAmr ibn Kulthūm in their famous dispute.",
    themes: [
      "fakhr",
      "hamasa",
      "hija",
      "hikma",
      "ghazal"
    ],
    signaturePoemIds: ["muallaqat-al-harith"],
  },
  {
    id: "al-akhtal",
    slug: "al-akhtal",
    nameAr: "الأخطل — غياث بن غوث التغلبي",
    nameEn: "Al-Akhtal (Ghiyath ibn Ghawth al-Taghlibi)",
    eraId: "umawi",
    birthYear: 640,
    deathYear: 710,
    region: "الجزيرة الفراتية (ديار تغلب، أعالي الفرات بين الموصل والرقة)",
    bioAr: "أبو مالك غياث بن غوث بن الصلت التغلبي، المعروف بالأخطل، شاعر نصراني من قبيلة تغلب الربعية، وأحد أركان النقائض الثلاثة في العصر الأموي مع جرير والفرزدق. نشأ في الجزيرة الفراتية على دين قومه النصرانية، وقرّبه يزيد بن معاوية ثم جعله عبد الملك بن مروان شاعر بلاطه الرسمي، ينافح عن دولة بني أمية ويهجو خصومها. اشتهر بجزالة لفظه ومتانة فخره وروائع خمرياته ووصفه، وكان أقدر الشعراء على مناهضة جرير، حتى أقرّ جرير بأن الأخطل غلبه في قصيدته «كذبتك عينك».",
    bioEn: "Abu Malik Ghiyath ibn Ghawth ibn al-Salt al-Taghlibi, known as al-Akhtal, was a Christian poet of the tribe of Taghlib (of Rabi'a) and one of the three masters of the naqa'id (poetic flytings) of the Umayyad age, alongside Jarir and al-Farazdaq. Raised in the Jaziran lands of the upper Euphrates in the Christian faith of his people, he was favored by Yazid ibn Mu'awiya and then made the official court poet of Abd al-Malik ibn Marwan, championing the Umayyad dynasty and lampooning its rivals. Famed for his robust diction, towering tribal pride, and masterly wine-poetry and description, he was the poet most able to stand against Jarir — who himself conceded that al-Akhtal bested him in the ode 'Kadhabatka aynuk.'",
    humanStoryAr: "كان الأخطل نصرانيّ تغلب وشاعر بني أمية، يدخل على عبد الملك بن مروان والصليب معلَّق في صدره يجرّ مطارف الخزّ، لا يُكلَّف بإسلامٍ ولا يُمنَع من خمرٍ، فيُنشد في حضرة الخليفة وقد فاحت منه الراح. ناصر الفرزدق على جرير ودخل معه حربه، فهجاه جرير بقوله في تغلب: «قوم إذا استنبح الأضياف كلبهم قالوا لأمهم بولي على النار»، وردّ الأخطل بأهجى ما قيل في كليب، حتى صار ثالوثهم من أخلد ما في الشعر العربي من مساجلات.",
    humanStoryEn: "Al-Akhtal was the Christian of Taghlib and the poet of the House of Umayya: he would enter upon Abd al-Malik ibn Marwan with a cross hung at his breast, trailing robes of silk, never pressed to convert nor barred from wine, reciting before the caliph with the scent of the cup upon him. He sided with al-Farazdaq against Jarir and entered their war, so that Jarir lampooned his tribe — 'A people whose dog, when guests set it barking, cry to their mother: piss on the fire!' — and al-Akhtal answered with some of the cruellest verse ever aimed at Banu Kulayb, until the three poets' rivalry became among the most enduring duels in all of Arabic poetry.",
    themes: ["hija", "fakhr", "ghazal"],
    signaturePoemIds: ["al-akhtal-khaffa-al-qatin", "al-akhtal-kadhabatka", "al-akhtal-liman-al-diyar"],
  },
  {
    id: "al-jahiz",
    slug: "al-jahiz",
    nameAr: "أبو عثمان عمرو بن بحر الجاحظ",
    nameEn: "Abū ʿUthmān ʿAmr ibn Baḥr al-Jāḥiẓ",
    eraId: "abbasi",
    region: "البصرة",
    bioAr: "أبو عثمان عمرو بن بحر الجاحظ (نحو 159–255هـ / 776–868م) أديب وعالم بصري من أعلام النثر العربي في العصر العباسي، صاحب أسلوب ساخر موسوعي، ومن أشهر مؤلفاته البخلاء والحيوان والبيان والتبيين.",
    bioEn: "Abū ʿUthmān ʿAmr ibn Baḥr al-Jāḥiẓ (c. 776–868 CE) was a Basran prose master and polymath of the Abbasid era, famed for his witty, encyclopedic style; his best-known works include al-Bukhalāʾ (The Misers), Kitāb al-Ḥayawān, and al-Bayān wa-l-Tabyīn.",
    humanStoryAr: "",
    humanStoryEn: "",
    themes: ["hikma"],
    signaturePoemIds: ["jahiz-bukhala"],
  },
  {
    id: "al-hariri",
    slug: "al-hariri",
    nameAr: "أبو محمد القاسم بن علي الحريري",
    nameEn: "Abu Muhammad al-Qasim ibn Ali al-Hariri",
    eraId: "abbasi",
    region: "البصرة",
    bioAr: "أديب ولغوي من البصرة (446–516هـ / 1054–1122م)، اشتهر بمقاماته الخمسين التي بلغت ذروة فن السجع والبديع في النثر العربي وغدت من أكثر كتب الأدب تداولاً وشرحاً.",
    bioEn: "A man of letters and philologist of Basra (1054-1122 CE), celebrated for his fifty Maqamat, which marked the pinnacle of rhymed prose (sajʿ) and rhetorical artistry in Arabic and became among the most widely read and commented works of Arabic literature.",
    humanStoryAr: "",
    humanStoryEn: "",
    themes: ["hikma"],
    signaturePoemIds: ["hariri-maqama"],
  },
  {
    id: "gibran",
    slug: "gibran",
    nameAr: "جبران خليل جبران",
    nameEn: "Khalil Gibran",
    eraId: "hadith",
    region: "بشري، لبنان / المهجر",
    bioAr: "جبران خليل جبران (1883–1931) أديب وشاعر ورسّام لبناني-أمريكي من أعلام أدب المهجر، هاجر إلى الولايات المتحدة وكتب بالعربية والإنجليزية، ومن أشهر مؤلفاته «النبي» و«الأرواح المتمردة» و«دمعة وابتسامة».",
    bioEn: "Khalil Gibran (1883–1931) was a Lebanese-American writer, poet, and painter, a leading figure of the Mahjar (emigrant) literary school. He emigrated to the United States and wrote in both Arabic and English; his best-known works include The Prophet, Spirits Rebellious, and A Tear and a Smile.",
    humanStoryAr: "",
    humanStoryEn: "",
    themes: ["hikma"],
    signaturePoemIds: ["gibran-prose"],
  },
];
